### ISSUE TITLE
Documentation for contructN and constructrN

### ISSUE THREAD

**Issue by Chaddai** [haskell/vector#10]
Hello, that's just a minor point and easily corrected but the documentation for constructN in Data/Vector.hs say : 

    -- > constructN 3 f = let a = f <> ; b = f <a> ; c = f <a,b> in f <a,b,c>

since `f` result is an element, I think you meant : 

    -- > constructN 3 f = let a = f <> ; b = f <a> ; c = f <a,b> in <a,b,c>

Same deal with constructrN.

**Comment by cartazio** [comment]
@Chaddai hello, document PRs are a bit easier to understand than tickets, if you dont mind doing that please have a go!
