### ISSUE TITLE
should we disable the O2 variant of the test suite?

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#106]
ie: only have O1 and O0 versions?
I seem to recall some folks were complaining about the excessive build times for vector CI now, and while I think having the test suite check with O2 is a good idea (heck, some of the long standing bugs we fixed in vector in the past year were only triggerable via O2), it is a trade off

**Comment by cartazio** [comment]
holy crap the build time still explodes at `O1`

@dolio @hvr @ekmett has anyone investigated how the test suite is exploding yet?

**Comment by cartazio** [comment]
@bgamari pointed me to https://ghc.haskell.org/trac/ghc/ticket/10800
i'm going to explore 1-2 ideas to make the test suite faster

**Comment by bgamari** [comment]
Thankfully this should be significantly better in GHC 8.0.1, as documented in [#10800 comments 16 and 17](https://ghc.haskell.org/trac/ghc/ticket/10800#comment:16).

**Comment by cartazio** [comment]
Yay. That's a strong argument for continuing the multiple optimization
levels test suite going forward. Both as a stress test of GHC and for
optimization bug hunting :)

**Comment by cartazio** [comment]
closing, vector O2 being slow has been good backpressure on ghc :)))
