### ISSUE TITLE
Feature request for uniq

### ISSUE THREAD

**Issue by andrewthad** [haskell/vector#107]
It would be nice to have `uniq` for operating on vectors. It would have the following type signature:

    uniq :: Eq a => Vector a -> Vector a

and it would remove any adjacent identical elements (like the linux program does). I'm just going to write this myself for a project I'm working on, but it would be nice to have one that I could trust to be efficient (since I'm not particularly good with optimizing haskell / reading core).

**Comment by cartazio** [comment]
@andrewthad did you write one in terms of monad streams or the like? are you thinking of a fusion friendly one or something different? the definition for streams should be straight forward, me and @dolio  are focusing on some other bits of vector the rest of the summer, but i'm happy to walk you through how to write the stream state machine for this

**Comment by andrewthad** [comment]
I didn't write a fusion-friendly one, but I would be interested in trying to do that. I'm busy with other things at the moment, but I'll try to come back to this in a few weeks.

**Comment by dolio** [comment]
I worry a little about the name `uniq`. Maybe put 'adjacent' in the name. Otherwise I'd expect people to think it's `nub` with a different name. Better names are also welcome.

**Comment by cartazio** [comment]
localNubEq? :)
streamingNubEq?

**Comment by dolio** [comment]
I said better names. :tongue:
