### ISSUE TITLE
Length doesn't seem to inline properly

### ISSUE THREAD

**Issue by gbaz** [haskell/vector#111]
As discussed here: http://stackoverflow.com/questions/36095925/why-vector-length-vector-replicate-n-0-is-not-fused

In simple test programs, `Data.Vector.Generic.length` seems to refuse to inline, for no apparent reason.

See #97 as perhaps related?

**Comment by gbaz** [comment]
In the SO discussion, it appears to be because in the latest Vector, ghc marks length as a loop-breaker.

**Comment by cartazio** [comment]
Huh, is that version of length not written in terms of length on stream /
bundle or as a worker wrapper?

**Comment by takano-akio** [comment]
I believe #155 fixes this.

**Comment by Shimuuar** [comment]
Finally fixed in #307
