### ISSUE TITLE
Foldable instance for Vector uses slow default implementations for many methods

### ISSUE THREAD

**Issue by mgsloan** [haskell/vector#112]
The current definition is

```haskell
instance Foldable.Foldable Vector where
  {-# INLINE foldr #-}
  foldr = foldr

  {-# INLINE foldl #-}
  foldl = foldl

  {-# INLINE foldr1 #-}
  foldr1 = foldr1

  {-# INLINE foldl1 #-}
  foldl1 = foldl1
```

The problem with this is that there are many other `Foldable` operations that have Vector versions which are much faster than the default implementations.  Sometimes Vector even offers an asymptotically superior version, such as `length`, which has an `O(n)` default implementation, whereas Vector has a `O(1)` operation for this.

I would open a PR, but was dissuaded by the pile of existing ones.

**Comment by winterland1989** [comment]
Please go ahead, this is clearly an optimazation which won't break any API, who is the maintainer now? Please make a judgement ; )

**Comment by Shimuuar** [comment]
> who is the maintainer now? 

I'd love to know answer to this question.

**Comment by dolio** [comment]
The core libraries committee is the official maintainer, and they delegate mostly to me.

If someone wants to implement this, it sounds like a good idea to me.

**Comment by Shimuuar** [comment]
Well judging by number of open pull requests and commit history there isn't enough manpower to maintain vector properly.

**Comment by cartazio** [comment]
could someone roll a wee benchmark to validate switching Data.Vector and suchlike to this?

Relatedly: I presume we can only provide a Foldable instance for boxed vectors right?

**Comment by dolio** [comment]
I implemented this. And yes, it's only for boxed vectors (`Foldable` could be implemented for unboxed vectors, but only by packing the dictionary in the type).
