### ISSUE TITLE
Use quot instead of div

### ISSUE THREAD

**Issue by andrewthad** [haskell/vector#115]
On this line https://github.com/haskell/vector/blob/224eccbac0125b7bd302f24063bbb473b2c2e1dc/Data/Vector/Storable.hs#L1337, `quot` can be used instead of `div` because its arguments cannot be negative. This should yield a (very) slight performance increase.

**Comment by cartazio** [comment]
Why would this result in a perf increase on modern hardware? Could you help
me understand how we would measure or validate such an assessment?

**Comment by andrewthad** [comment]
I had always been told that `quot` is faster because CPUs have a specific instruction for it but not for `div`. I just threw together a little criterion program to compare them, and it looks like they do in fact have the same performance.

**Comment by cartazio** [comment]
I suspect part of the tricky bit there is that modern CPUs have a lot of
work done to make branch prediction super good. At least as long as inner
loop or whatever code has a sufficiently biased branch etc


@ Andrew : the Intel optimizations manual is a treasure trove of good
optimization examples and explaining the cost model / medium inner workings
of how to write fast code for a modern cpu. You may find a lot of fun /
good ideas there to experiment with for vector or better yet ghc ;)

Either way, excellent question and I hope my reply / nudge was helpful :)

**Comment by cartazio** [comment]
closing pending benchmark or bug related to this :)
