### ISSUE TITLE
Tackling the test suite todo list.

### ISSUE THREAD

**Issue by archblob** [haskell/vector#12]
I would happily implement everything on the todo list from the test suite if someone thinks they can find the time to review and merge the code once I'm done and everything is ok. So, if you think it's worthwhile, is someone willing to review my code if I go ahead with this ?

**Comment by cartazio** [comment]
@archblob i forget which todolist this was, could you remind me ? :(

**Comment by archblob** [comment]
Things did not go as planned.:)
The testsuite is littered with ``TODO``s about untested functions.
