### ISSUE TITLE
GenUnboxTuple out of date

### ISSUE THREAD

**Issue by andrewthad** [haskell/vector#120]
The [GenUnboxTuple](https://github.com/haskell/vector/blob/1480fafa52e4944c6a2d0dca602af7786a58901a/internal/GenUnboxTuple.hs) file, which is used to generate the unboxed vector instances for tuples, doesn't include definitions for `basicInitialize`. This is not really a problem, since it looks like someone added them by hand, but it would be nice if the generated code actually matched what the code generator outputted.

**Comment by cartazio** [comment]
@dolio whats your take on what we should do here? def room for code cleanup

**Comment by dolio** [comment]
I'll fix it. I didn't realize there was code for generating the things I manually edited.
