### ISSUE TITLE
Allow all MVector operations under `PrimMonad`

### ISSUE THREAD

**Issue by dogirardo** [haskell/vector#137]
In particular, most pure MVector functions are only possible when addressing is statically known.

Imagine an indexed vector, with elements of unknown size and a bundled index vector mapping element index into pointer offset. In this case, most operations must access the indexing vector (under the `PrimMonad`) to translate addresses. Ex: `basicUnsafeSlice`, `basicOverlaps` etc. 
The above example is impossible to give an `MVector` instance AFAIK

**Comment by cartazio** [comment]
Could you give some pseudo code to explain what you mean?

Slicing / range metadata is always pure, but how it's exposed depends on
the specific vector rep.  So I'm not sure what you mean.

**Comment by dogirardo** [comment]
Sorry, I should clarify, I'm talking about the Generic `MVector` class, not any implementation in `vectors`

A simplified motivating example is
```haskell

data MVector s a = MVector
    {payload :: !(ForeignPtr Word8)
    ,byteOffset :: !Int
    ,byteLength :: !Int
    ,indexVector :: !(VUM.MVector s Int)}
```

The `payload` contains packed serialized data of variable length (ex: text), which can be walked/streamed sequentially, while `indexingVector` maps element index into byte index for fast element indexing as well. In this case, the slicing metadata is not pure, and requires a read into `indexingVector` to figure out how to slice the raw bytes.

**Comment by cartazio** [comment]
What specific operation or example program are you trying to write but are
unable to? I need you to spell everything out

What mvector operation currently has a type you dislike and what is that
current type and what would the type you desire be.

Please spell these out

**Comment by dogirardo** [comment]
So here's one example. Not totally correct but it gets the point across

Currently:
```haskell
basicUnsafeSlice :: Int -> Int -> v s a -> v s a	
```
Desired:
```haskell
basicUnsafeSlice :: PrimMonad m => Int -> Int -> v (PrimState m) a -> m (v (PrimState m) a)
```
Implementation using the above defined concrete `MVector`:
```haskell

basicUnsafeSlice' :: (PrimMonad m) => Int -> Int -> MVector (PrimState m) a -> m (MVector (PrimState m) a)
basicUnsafeSlice' i j (MVector fp off _ is) = do
    i' <- VGM.basicUnsafeRead is i
    j' <- VGM.basicUnsafeRead is (i+j)
    let l' = j' - i' + 1
    return $ MVector fp (off+i') l' (VGM.unsafeSlice i j is)
```

**Comment by cartazio** [comment]
If the metadata about array structure isn't pure , or can't be safely
treated as pure, everything in vector essentially breaks.  I think @dolio
should chime in too, but my take is that this feature request is actually
your code telling you arrays need immutable metadata if you want to use
them with vector :)

**Comment by dogirardo** [comment]
The immutable version of the above has pure metadata, but for the mutable one metadata cannot safely be treated as pure. Yet, maybe I misunderstand something about `vector`, how does it break everything?

**Comment by cartazio** [comment]
If you can't make the metadata pure, then it can't be a legal mvector
instance.  You're essentially trying to have a UTF8 encoded string with
constant time grapheme updates, but that in general requires resizing the
buffer / allocating a new one.

Rethink your problem. Or resize it :)

**Comment by dogirardo** [comment]
So, `Phased`? ;)

**Comment by cartazio** [comment]
I do agree that some good mutable / pure data structures for that
UTF8/grapheme stuff would be good, and I hope I'm interpreting the context
/ goal correctly. I just think that vector and mvector aren't quite the
right interface or layer for it. Unless you love boxing ;) or working with
respect to unboxed 32bit code points

**Comment by dolio** [comment]
Sorry for being a bit late to the party here.

But yes, I don't think vector can realistically support your use case. Changing all the slicing/sizing functions to be effectful alone would be a major change, and probably break most consumers of the library.

But more than that, I don't think the API fits your needs in other ways, either. For instance, how do you allocate one of these arrays? You only receive a number of elements in new, not the size of each one, which you must know a priori to allocate sufficient space. And what happens if you want to write a larger element than the one that currently exists at an index? Does everything after it shift?

So I agree, what we're running into here is that the meta data must be pure/static anyway, at least to be backed efficiently by the unboxed arrays exposed by vector/primitive. Perhaps there are special cases that would be efficient for this sort of vector, but I'm not sure it's worth breaking compatibility with a bunch of packages to support those.

**Comment by dogirardo** [comment]
Agreed, it doesn't make sense to mutate these within the vector framework. In practice I'm using a mutable builder to only `snoc` elements sequentially / grow before freezing.
However, I think it's a perfectly good immutable `Vector` implementation - is there a reason I'm missing for why `MVector` is a necessary superclass of `Vector`? Is that worth a separate issue?

**Comment by cartazio** [comment]
That is a necessary requirement of how the fusion framework works.  You
can't get fusion without it for a lot of technical reasons related to how
vector is designed.

**Comment by cartazio** [comment]
I suggest you try writing your own array interface for your experiments.
Pure metadata is a really important thing for most mutable array libraries,
and the mvector => vector type class structure is needed for way the vector
library does fusion.
