### ISSUE TITLE
Please add support for QuickCheck 2.9.x

### ISSUE THREAD

**Issue by peti** [haskell/vector#138]
The test suite constrains `QuickCheck ==2.7.*`, but that restrictions seems unnecessary, i.e. the build works fine if that version range is extended to incude 2.8.\* (and possibly 2.9.x as well, though I didn't test that).

**Comment by hvr** [comment]
@peti not sure what you mean, current Git master allows *only* `QuickCheck==2.9.*` since 
31edb3fc51e76facc1e291f1e9e721663d91dbd8

**Comment by peti** [comment]
Well, `cabal install vector` doesn't use the git repository, unfortunately. The restriction seems to be still in place on the latest Hackage release.

**Comment by hvr** [comment]
I see; well for the released version QuickCheck 2.9 wouldn't work due to some orphan instance collision. So at best the upper bound could be relaxed allow 2.8.*. Just wondering, what benefit does it have for you if the testsuite is able to use a newer QC version?

**Comment by peti** [comment]
With the relaxed constraint the package would compile in an LTS 7.x package set, which mandates QC 2.8.x.

**Comment by peti** [comment]
In LTS 8.x, which has QuickCheck version 2.9.2, the test suite no longer compiles at all.

**Comment by RyanGlScott** [comment]
For the sake of being explicit, here is the error that I think @peti is alluding to:

```
rgscott@gearloose:~/.../Hacking/Haskell/vector-0.12.0.0$ cabal build
Building vector-0.12.0.0...
Preprocessing library vector-0.12.0.0...
Preprocessing test suite 'vector-tests-O0' for vector-0.12.0.0...
[6 of 6] Compiling Main             ( tests/Main.hs, dist/build/vector-tests-O0/vector-tests-O0-tmp/Main.o )

tests/Main.hs:4:1: error:
    Failed to load interface for ‘Tests.Vector.UnitTests’
    Use -v to see a list of the files searched for.
```

This should an easy fix. I'll work on it.

**Comment by RyanGlScott** [comment]
This has been fixed upstream. Now we just need to upload a new minor release to get the tests back on nixpkgs/Stackage.
