### ISSUE TITLE
Feature request for nub

### ISSUE THREAD

**Issue by centromere** [haskell/vector#145]
It would be wonderful if the `nub` and/or `nubBy` functions from [Data.List](http://hackage.haskell.org/package/base-4.9.0.0/docs/Data-List.html#v:nub) were supported.

**Comment by dolio** [comment]
Should be doable. Is the O(n*k) (length n, unique elements k) algorithm acceptable? I think the O(n*lg k) algorithm would require dependencies we don't have yet.

**Comment by centromere** [comment]
Yes, that's fine.

**Comment by 3noch** [comment]
`uniq` is present but `uniqBy` is not.

**Comment by Boarders** [comment]
Just ran into a problem where this would be nice to have!

**Comment by Bodigrim** [comment]
This is now covered by https://hackage.haskell.org/package/vector-algorithms-0.9.0.1/docs/Data-Vector-Algorithms.html#v:nub
