### ISSUE TITLE
Is it possible to use Coercible on Unboxed vectors?

### ISSUE THREAD

**Issue by wyager** [haskell/vector#148]
I was looking into using `Data.Coerce` for coercing between `Vector`s of Dimensional types from `Numeric.Units.Dimensional` and `Vector`s of their underlying field (`Double`s, in this case). 

It works fine for `Data.Vector` and even `Data.Vector.Storable`. However, it doesn't work on `Data.Vector.Unboxed`. I suspect this is because GHC automatically infers a `nominal` role for the parameter `a` of `Data.Vector.Unboxed.Vector a` due to the use of type families. 

I can see why this behavior makes sense (one could provide an incompatible `Unbox` instance for a newtype wrapper), but then perhaps the same thing should apply for `Data.Vector.Storable`.

Here's a quick demo output from GHCi:

```
import qualified Data.Vector.Storable as VS
import qualified Data.Vector.Unboxed as VU
import Data.Coerce
import Numeric.Units.Dimensional
import Numeric.Units.Dimensional.SIUnits
import Numeric.Units.Dimensional.Coercion
coerce (VS.singleton (1 :: Double)) :: VS.Vector (Length Double)
[1.0 m]
coerce (VU.singleton (1 :: Double)) :: VU.Vector (Length Double)

<interactive>:15:1: error:
    • Couldn't match type ‘Double’
                     with ‘Dimensional
                             'Numeric.Units.Dimensional.Variants.DQuantity DLength Double’
        arising from a use of ‘coerce’
    • In the expression:
          coerce (VU.singleton (1 :: Double)) :: VU.Vector (Length Double)
      In an equation for ‘it’:
          it
            = coerce (VU.singleton (1 :: Double)) :: VU.Vector (Length Double)
```

**Comment by cartazio** [comment]
Unless you are very careful, in general coercionable will not be valid for
storable or unboxed values

**Comment by wyager** [comment]
I agree. Perhaps it would be wise to add a `type role nominal` declaration to Data.Vector.Storable. 

On the other hand, perhaps not. `coerce` is very powerful for high-performance computation where `Vector` might be most useful, and `Storable` instances are already unsafe if used improperly.

`Dimensional` somehow makes you import a `.Coercion` module before you can use `coerce`. Maybe we could do the same for `Vector.Storable` and put an appropriate warning?

**Comment by cartazio** [comment]
Unsafe coerce could use used internally in the code you're writing to make
the coercions when you know the only differences in representations are
phantom arguments. Just bundle it up in a safe interface. Performance
doesn't enter the picture.

But in general I think coercible is only safe for storable and unboxed if
and if you apriori can assert that the alignment and serialization rep are
defined to the same. At which point you can make the O(1) transformation
yourself using unsafe coerce wrapped up safe.

That said maybe I'm missing a key part of your suggestion.

**Comment by wyager** [comment]
The whole point of `Coercible` is to be safe, as opposed to `Unsafe.Coerce`. Normally, `Coercible` is safe by construction (and it resolves the issues with `GeneralizedNewtypeDeriving` and `TypeFamilies` via the introduction of type roles). `Storable` subverts this safety by opaquely using unboxed memory representations that might change across representation-equivalent types.

I'm willing to give `Storable` a pass because it lives in IO, which is allowed to do things like arbitrary memory writes. But, as a heuristic, pure code shouldn't do anything memory-unsafe without being quite loud about it  (for example, all functions in `Vector` that are memory-unsafe start with `unsafe`). 

However, `Vector` uses `unsafeInlineIO` to hide the use of `Storable` in a pure function. 

The fact that `a` in `Data.Vector.Storable.Vector a` has a `representational` role means that some unsuspecting person could use a combination of theoretically safe operations (`coerce` and any "safe" vector operation) to perform illegal memory accesses in pure code. 

My current  thought is that perhaps we should *force* people to use `unsafeCoerce` instead of `coerce` in `Data.Vector.Storable`, so they know what they're getting into. 

My original question was if it was possible to somehow `coerce` unboxed vectors, but I now think that this probably isn't a good idea, and neither is allowing `coerce` on Storable vectors.

**Comment by Shimuuar** [comment]
Storable vector is nominally since #235 was merged. Closing this issue.
