### ISSUE TITLE
Feature request for partitionEithers

### ISSUE THREAD

**Issue by andrewthad** [haskell/vector#154]
Having the vector analogue of [partitionEithers](http://hackage.haskell.org/package/base-4.9.1.0/docs/Data-Either.html#v:partitionEithers) from `Data.Either` would be nice. This would improve upon the [partition](http://hackage.haskell.org/package/vector-0.12.0.0/docs/Data-Vector.html#v:partition) currently available in `Data.Vector`. I could take a stab at this if others agree that it's appropriate for this library.

**Comment by dolio** [comment]
Sounds like a good idea to me.

**Comment by andrewthad** [comment]
I started working on this, and I quickly realized that the signature from function provided by `Data.Either` is not really optimal. If we adopted it, the vector function would be:

    partitionEithers :: Vector (Either a b) -> (Vector a, Vector b)

This is problematic for unboxed and storable vectors, and it's not really consistent with the way that `partition` in `Data.Vector` works. It also doesn't lend itself well to a possible unstable version that could be added in the future. I would much prefer:

    partitionEither :: (a -> Either b c) -> Vector a -> (Vector b, Vector b)

But I think it should have a different name.

**Comment by cartazio** [comment]
Unshuffle? Unruffle? PartitionBy?

A related API that is worth looking at is the witherable package

**Comment by RyanGlScott** [comment]
GHC itself uses the name [`partitionWith`](http://git.haskell.org/ghc.git/blob/dae50032c1f17e49d115c853752259c35cc9840c:/compiler/utils/Util.hs#l287).

**Comment by andrewthad** [comment]
I finally got around to doing this. Would someone mind looking over it?

**Comment by Shimuuar** [comment]
partitionWith is released in 0.12.1
