### ISSUE TITLE
Algorithm request: sorting 

### ISSUE THREAD

**Issue by ocramz** [haskell/vector#157]
Would it be possible to include some sorting algorithms, such as those that appear in `vector-algorithms` ?

Paging also @dolio for an opinion ..

**Comment by cartazio** [comment]
What's wrong with depending on vector algorithms...?
It's pretty darn stable

**Comment by ocramz** [comment]
Of course one currently has to depend on `vector-algorithms`, but it's very confusing to a beginner why doesn't `vector` offer any sorts and where to find these.

**Comment by cartazio** [comment]
While I agree with the spirit of what you're saying, I disagree with the choice of approach.  

I think we'd be happy to compile a time stamped "updated as of xxxyyy" style opinionated listing of related / complementary tools to vector , adding vector algorithms to vector is too tight a coupling and would incur a lot of complexity. 

Also no matter what single sorting alg, it'll be the wrong choice ;)

**Comment by cartazio** [comment]
So I'm going to close this ticket wrt the suggested course of action, but I agree with the small opinionated  friends of vector kinda list.  Though how to do that without drama is a separate topic I can't opine on

**Comment by ocramz** [comment]
@cartazio Yeah I understand this is not a bug per se, but an opportunity to make the library interface a tiny bit more friendly. Should I file a PR for the README file re. this ?

**Comment by cartazio** [comment]
That sounds like a decent starting point.

And or open a new issue for tracking the discussion and let's put a page on
the Haskell wiki?  Idk. Pr/ in issue discussion before putting it somewhere
might be best?
