### ISSUE TITLE
Growing Primitive Vectors

### ISSUE THREAD

**Issue by andrewthad** [haskell/vector#164]
Reading through [an issue about the semantics of `grow`](https://github.com/haskell/vector/issues/36), I learned that `vector` doesn't ever try to grow primitive vectors in place. I would like to add support for this behavior. I've put together an untested PR which uses `resizeMutableByteArray#` to change this behavior. I think that all of the documentation-related concerns from the original issue I reference are still valid. The docs need to explain that after growing a mutable vector, the original one should not be used anymore.

**Comment by cartazio** [comment]
Have you included benchmarks? Is it faster?

**Comment by andrewthad** [comment]
Not sure yet. I'll get on that.

**Comment by andrewthad** [comment]
It turns out that the [implementation of resizeMutableByteArray#](https://git.haskell.org/ghc.git/commitdiff/246436f13739593d2a211ceb830393338118ca4d) always reallocates when you grow a `ByteArray#`. The benchmarks I've added to my PR confirm this. The performance is unaffected when `resizeMutableByteArray#` is used. I'm going to leave my PR up in case `resizeMutableByteArray#` is ever improved.

**Comment by cartazio** [comment]
Cool and thanks for investigating.  Close the pr for now though :)

**Comment by dolio** [comment]
FYI, the other problem with this would be that it'd only be valid to grow the array in place if we haven't sliced it already. Or, I suppose it could be valid, but it'd be a significant semantic change from what currently happens.
