### ISSUE TITLE
should we strengthen basic overlaps and or add an "unslice" api

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#170]
```haskell

unsliceM ::  DVM.MVector s a -> DVM.MVector s a -> Maybe (DVM.MVector s a )
unsliceM mv1@(DVM.MVector base1 len1 arr1) mv2@(DVM.MVector base2 len2 arr2)
      | not $ GVM.basicOverlaps mv1 mv2 = Nothing
      | base2 == base1 + len1 = Just $  DVM.MVector base1 (len1 + len2) arr1

```
is one exmaple of what i think the unslice could be. I"m not sure if its experssive with the current vector typeclass api, though it should be expressible for each of the standard vector families i think

**Comment by Shimuuar** [comment]
Such functionality isn't very useful and _very_ tricky to implement correctly. One have to deal with structure of arrays for unboxed vectors. For storable vectors we need to make sure that both slices have same finalizer. 

On top of that semantic of overlap is not clear. See #88, #472. Overall I think juice doesn't worth the squeeze.

I propose closing as WONTFIX

**Comment by lehins** [comment]
> I propose closing as WONTFIX

Concur
