### ISSUE TITLE
slice doesn't say in haddocks that the second index is inclusive

### ISSUE THREAD

**Issue by nh2** [haskell/vector#173]
I somehow thought `slice` was inclusive, but it is not:

```
V.slice 0 2 $ V.fromList [0..5]
[0,1]
```

Would be great to have that info in the Haddocks.

**Comment by glguy** [comment]
This is documented already, the second parameter is not an index at all, it's a length

**Comment by nh2** [comment]
> This is documented already.

@glguy Is it? For me https://hackage.haskell.org/package/vector-0.12.0.1/docs/Data-Vector-Mutable.html#v:slice just says `Yield a part of the mutable vector without copying it.`

**Comment by glguy** [comment]
Yes, the slice you were using is actually this one (mutable vectors don't have fromList)

http://hackage.haskell.org/package/vector-0.12.0.1/docs/Data-Vector.html#v:slice

The whole Mutable module could use much more documentation, however.

**Comment by nh2** [comment]
Fixed by #227.
