### ISSUE TITLE
group and groupBy

### ISSUE THREAD

**Issue by andrewthad** [haskell/vector#192]
In `Data.List`, we have:

    group :: Eq a => [a] -> [[a]]
    groupBy :: (a -> a -> Bool) -> [a] -> [[a]]

I would like to introduce analogous version into `vector`:

    group :: Eq a => Vector -> [Vector a]
    groupBy :: (a -> a -> Bool) -> Vector a -> [Vector a]

These have the potential to be much more space efficient than the list equivalents since they share the underlying array with the original vector. Would this be accepted if I added it?

**Comment by radrow** [comment]
I actually need this feature, it would be really cool if this could be added

**Comment by andrewthad** [comment]
Do any of the maintainers have any thoughts on this?

**Comment by cartazio** [comment]
I think something like this might work.  But would the result be a list of
vectors or rather a vector of vectors ?

Could we make this play nice with stream fusion or not?

**Comment by radrow** [comment]
That's a good question - if somebody wants to play with vectors he won't probably want to use lists suddenly at same place. From the other hand he will not need random access at the start, because placement and number of groups is quite unpredictable.

**Comment by andrewthad** [comment]
There is a little bit of precedent for using list instead of vector. Consider the signature for Data.Vector.concat, which takes a list and not a vector. I think list is probably a better choic here because it means that the the type signature for the Unboxed vector variant will be consistent.

**Comment by BebeSparkelSparkel** [comment]
[Data.StorableVector.groupBy](https://hackage.haskell.org/package/storablevector-0.2.13/docs/Data-StorableVector.html#v:groupBy)

**Comment by tchoutri** [comment]
Would love to see this happen as well!
