### ISSUE TITLE
Explain `cons` and `snoc` performance

### ISSUE THREAD

**Issue by taktoa** [haskell/vector#202]
[`Data.Vector.cons`](https://hackage.haskell.org/package/vector-0.12.0.1/docs/Data-Vector.html#v:cons) and [`Data.Vector.snoc`](https://hackage.haskell.org/package/vector-0.12.0.1/docs/Data-Vector.html#v:snoc) are both _O(n)_ operations for vectors of length _n_.

I think the Haddock documentation should explain why this is the case ("because `Vector`s are persistent"), note the behavior in the case of fusion (I don't know whether `cons` can achieve amortized _O(1)_ performance under fusion), and perhaps have a loud "WARNING".

**Comment by andrewthad** [comment]
Agreed.
