### ISSUE TITLE
Is `NoRepType` right for immutable vectors?

### ISSUE THREAD

**Issue by andy-morris** [haskell/vector#204]
The following GHCI session illustrates what I'm talking about:

```
λ» :set -XOverloadedLists 
λ» :m Data.Set Data.Vector Data.Generics.Uniplate.Data

λ» getInts xs = universeBi xs :: [Int]

λ» getInts ([1, 2, 3] :: [Int])
[1,2,3]

λ» getInts ([1, 2, 3] :: Set Int)
[1,2,3]

λ» getInts ([1, 2, 3] :: Vector Int)
[]
```

Since all vectors declare themselves to be `NoRepType`s, the uniplate library (and probably others) immediately stop traversing on encountering a vector. This seems to me like it's probably not the intended behaviour for immutable vectors. (For mutable ones it's a different matter, of course.)

So, unless I'm mistaken, I'd like to suggest that immutable vector types follow the lead of `Set` and friends, and have `Data` instances along the lines of the following (but presumably defined once and for all in `...Generic` like now):

```haskell
instance Data a => Data (Vector a) where
    gfoldl f z m   = z fromList `f` toList m
    toConstr _     = fromListConstr -- was: error "toConstr"
    gunfold k z c  = case constrIndex c of -- was: error "gunfold"
        1 -> k (z fromList)
        _ -> error "gunfold"
    dataTypeOf _   = vectorDataType -- was: mkNoRepType "Data.Vector.Vector"
    dataCast1 f    = gcast1 f

fromListConstr :: Constr
fromListConstr = mkConstr vectorDataType "fromList" [] Prefix

vectorDataType :: DataType
vectorDataType = mkDataType "Data.Vector.Vector" [fromListConstr]
```

**Comment by RyanGlScott** [comment]
Indeed, the current `Data` instances seem strangely inconsistent, with we implement `gfoldl f z m = z fromList `f` toList m` but don't implement other methods in a similar fashion.

Your proposed implementation sounds sensible to me—care to make a pull request?

**Comment by andy-morris** [comment]
You probably saw, but if not, I've put it in #205.
