### ISSUE TITLE
Consider removing `semigroups` dependency

### ISSUE THREAD

**Issue by vrom911** [haskell/vector#217]
I've noticed that `semigroups` package is used in this library. But it's quite a heavy dependency. Since `Semigroup` typeclass is in `base` package for quite a long time, probably it makes sense to optimize dependencies footprint. This will make `vector` package really small and better fit for libraries who really care about their number of dependencies.

**Comment by RyanGlScott** [comment]
We only depend on `semigroups` if you're building with a GHC older than 8.0 (i.e., before `Semigroup` was added to `base`):

https://github.com/haskell/vector/blob/65cfe828f5bddf59fd5aaaead96c5ad45ecd7a8d/vector.cabal#L153-L154

So the dependency footprint is already as light as we can possibly make it with respect to the `Semigroup` class.
