### ISSUE TITLE
Please bump base upper bound for GHC 8.6.1

### ISSUE THREAD

**Issue by lambdageek** [haskell/vector#218]
GHC 8.6.1 will have 4.12, please bump to `base >= 4.5 && < 4.14` 
https://github.com/haskell/vector/blob/master/vector.cabal#L150

**Comment by RyanGlScott** [comment]
I've done this in `master` in 919bd41. @cartazio, can you make the corresponding revision on Hackage?

**Comment by cartazio** [comment]
Roger.  I’ll get to it later today

**Comment by cartazio** [comment]
i assume we should be doing < 4.13?  (not sure why 4.14 was suggested?)

did the bump for 0.12.0.1

@ Ryan: let me know if further action is needed

**Comment by RyanGlScott** [comment]
> i assume we should be doing < 4.13?  (not sure why 4.14 was suggested?)

Indeed, I bumped it to `< 4.13` in 919bd413629f8a7f7346d11d5be4435b2476569a.

> did the bump for 0.12.0.1

Thanks, @cartazio!
