### ISSUE TITLE
newer QuickCheck

### ISSUE THREAD

**Issue by clinty** [haskell/vector#222]
please relax upper bounds on QuickCheck

**Comment by cartazio** [comment]
i'll do it to the repo  after quickcheck gets a < 1.2 bound for random. (the next release of random has breaking changes, so before i ship it i'll need to do some due diligence there with some hackage trustees)

have you tested with newer quickcheck / whats your blocker?

in the mean time, please dont mind it and just allow newer.

**Comment by cartazio** [comment]
should be fixed
