### ISSUE TITLE
`Data.Vector.Unboxed.Vector Bool` could use a bitarray internally

### ISSUE THREAD

**Issue by vaibhavsagar** [haskell/vector#236]
The `array` library [seems to specialise the implementation of `UArray Bool`](http://hackage.haskell.org/package/array-0.5.3.0/docs/src/Data.Array.Base.html#line-508). Could unboxed vectors of `Bool` be similarly optimised?

**Comment by cartazio** [comment]
unboxed vectors ARE always specialized.

bit vector representation though? you can absolutely do that in user space, but it doesn't play well with supporting efficient writes as well as reads (or at least the main platforms ghc lives on dont support such). And thats ignoring the issue of thread safety for concurrent reads/writes. Normal reads/writes to a memory location dont conflict with eachother if they're to different positions, whereas with the bitvector rep you lose that safety. 

So, nope, We wont add that to vector. you could totally define a newtype Bit = MkBit Bool, and define the unboxed vector rep to be the bit vector one yourself though!

(i do agree it saves space, and has uses, but bool wont get it in unboxed vector)

**Comment by vaibhavsagar** [comment]
In case anyone else also wants this, it turns out there is http://hackage.haskell.org/package/bitvec.
