### ISSUE TITLE
semantics of monad fail for vector

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#241]
@RyanGlScott 

I noticed the semantics you give doesn't match the previous one!

```

#if !(MIN_VERSION_base(4,13,0))
  {-# INLINE fail #-}
  fail = Fail.fail
#endif

instance Fail.MonadFail Vector where
  {-# INLINE fail #-}
  fail _ = empty

```

before fail would just return a mzero of the vector, aka the empty vector, now we get an exception? was this a copy pasta of patches or DO we want that? it seems like the PR was incorrect. @andrewthad, is there some insight i'm missing, or is this just flat out wrong as merged?

**Comment by cartazio** [comment]
https://github.com/haskell/vector/pull/238

**Comment by cartazio** [comment]
I did a naive fixup on master, BUT only in the sense of making the two fails equal, and returning mzero. whether they should actually invoke fail/error instead is a different question! (change in semantics etc)

question 1:  when would we get a desugaring with fail? theres only one constructor !

question 2: is it used anywhere?

question 3: should we jsut remove fail?! 

question 4: if we keep fail, which semantics, old one or breaking change with error/fail?

**Comment by RyanGlScott** [comment]
I certainly didn't intend to change the semantics of the existing `fail` implementation. That being said, I disagree with this statement:

> before fail would just return a mzero of the vector, aka the empty vector, now we get an exception?

I'm not sure how you reached this conclusion. `fail` should still return the empty vector, so I'm not sure where this business about exceptions enters the picture.

**Comment by cartazio** [comment]
how would `Fail.fail` return the empty vector?

**Comment by cartazio** [comment]
ohhh, i cant READ

**Comment by cartazio** [comment]
gotcha, i'm dumb

**Comment by cartazio** [comment]
cpp confusion on the brain, my bad

**Comment by RyanGlScott** [comment]
No worries!

Ultimately, it's not of terrible importance whether we pick `fail = Fail.fail` or `fail _ = empty`, as both are semantically equivalent. The reason I went with the former is that the `-Wcompat` flag will warn (on old versions of GHC) if your `fail` implementations aren't literally of the form `fail = Fail.fail`. We're not using `-Wcompat` in `vector`, of course, but I usually consider it good style anyway.
