### ISSUE TITLE
Export data constructor for boxed vector

### ISSUE THREAD

**Issue by andrewthad** [haskell/vector#245]
The module `Data.Vector` does not export the data constructor for `Vector`. Exporting this would make it possible to use `vector`'s functions in contexts where I am working with an unsliced `Array` and want to fold over a slice of it. In general, I would like to see all of the data constructors exported.

@cartazio In https://github.com/haskell/vector/issues/49, this is the same position you take. Do you still agree?

**Comment by chessai** [comment]
I have also wanted this on numerous occasions.

**Comment by cartazio** [comment]
Ill reread everything and then think about it. Don’t have vector loaded
into my head atm.

But speculative yes to making the constructor public at least in an
internal module

**Comment by Shimuuar** [comment]
I think exporting constructor from Data.Vector is wrong. It's trivial to create memory unsafe vector value: `Vector 0 10000 []`. It's probably better to export it from some `*.Internal` module. It would make obvious that it is dangerous.

**Comment by andrewthad** [comment]
I don't care what module it comes from. Either `Data.Vector.Unsafe` or `Data.Vector.Internal` would be fine to me.

**Comment by cartazio** [comment]
Yeah. We’re all on the same page.

**Comment by lehins** [comment]
Fixed in #434 by providing functions that give access to boxed Vector's internal `Array`
