### ISSUE TITLE
Possible bug?: zipWithM xs xs rule

### ISSUE THREAD

**Issue by gksato** [haskell/vector#252]
Hello. I've been lately reading the source of this package, and I found the rules like
``` Haskell
{-# RULES

"zipWithM xs xs [Vector.Stream]" forall f xs.
  zipWithM f xs xs = mapM (\x -> f x x) xs   #-}
```
in Data.Vector.Fusion.Stream.Monadic and Data.Vector.Fusion.Bundle.Monadic. These rules look like bugs to me, since the meanings of the two sides of the equation are different. Note that streams/bundles in these modules are *monadic* --- the left hand side duplicates and interleaves the actions in the two copies of the stream xs, and the right hand side executes each of the actions only once.

One possible interpretation is that these Monadic Fusion modules are _internal_ and it is intended only for use from vector modules, but it does not seem to be documented. What do you think?

**Comment by cartazio** [comment]
@gksato very good question, and its kinda subtle! (though i think you're correct perhaps?)
```haskell
-- | Result of taking a single step in a stream
data Step s a where
  Yield :: a -> s -> Step s a
  Skip  :: s -> Step s a
  Done  :: Step s a

instance Functor (Step s) where
  {-# INLINE fmap #-}
  fmap f (Yield x s) = Yield (f x) s
  fmap _ (Skip s) = Skip s
  fmap _ Done = Done

-- | Monadic streams
data Stream m a = forall s. Stream (s -> m (Step s a)) s


-- | Zip two 'Stream's with the given monadic function
zipWithM :: Monad m => (a -> b -> m c) -> Stream m a -> Stream m b -> Stream m c
{-# INLINE_FUSED zipWithM #-}
zipWithM f (Stream stepa ta) (Stream stepb tb) = Stream step (ta, tb, Nothing)
  where
    {-# INLINE_INNER step #-}
    step (sa, sb, Nothing) = liftM (\r ->
                               case r of
                                 Yield x sa' -> Skip (sa', sb, Just x)
                                 Skip    sa' -> Skip (sa', sb, Nothing)
                                 Done        -> Done
                             ) (stepa sa)

    step (sa, sb, Just x)  = do
                               r <- stepb sb
                               case r of
                                 Yield y sb' ->
                                   do
                                     z <- f x y
                                     return $ Yield z (sa, sb', Nothing)
                                 Skip    sb' -> return $ Skip (sa, sb', Just x)
                                 Done        -> return $ Done

-- FIXME: This might expose an opportunity for inplace execution.
{-# RULES

"zipWithM xs xs [Vector.Stream]" forall f xs.
  zipWithM f xs xs = mapM (\x -> f x x) xs   #-}

```

**Comment by cartazio** [comment]
now, Vector.Generic has it defined thusly 

```
-- | /O(min(m,n))/ Zip the two vectors with the monadic action and yield a
-- vector of results
zipWithM :: (Monad m, Vector v a, Vector v b, Vector v c)
         => (a -> b -> m c) -> v a -> v b -> m (v c)
-- FIXME: specialise for ST and IO?
{-# INLINE zipWithM #-}
zipWithM f = \as bs -> unstreamM $ Bundle.zipWithM f (stream as) (stream bs)
```

Bundle has 

```
zipWithM :: Monad m => (a -> b -> m c) -> Bundle v a -> Bundle v b -> M.Bundle m v c
{-# INLINE zipWithM #-}
zipWithM f as bs = M.zipWithM f (lift as) (lift bs)
```

which goes to Monadic Bundle 
```haskell

-- | Zip two 'Bundle's with the given monadic function
zipWithM :: Monad m => (a -> b -> m c) -> Bundle m v a -> Bundle m v b -> Bundle m v c
{-# INLINE_FUSED zipWithM #-}
zipWithM f Bundle{sElems = sa, sSize = na}
           Bundle{sElems = sb, sSize = nb} = fromStream (S.zipWithM f sa sb) (smaller na nb)

-- FIXME: This might expose an opportunity for inplace execution.
{-# RULES

"zipWithM xs xs [Vector.Bundle]" forall f xs.
  zipWithM f xs xs = mapM (\x -> f x x) xs   #-}
```
which then goes back to where we started

**Comment by RyanGlScott** [comment]
As far as I understand it, any concrete instantiation of `vector`'s fusion framework in the `vector` library itself will use the identity monad (i.e., `Id`) as the `m` in `Bundle m v a`, which means that the order of effects is irrelevant due to the fact that you can't observe them in `Id`. I suppose the situation would be different if we chose a different `m`, however—does this ever happen in the wild?

(Disclaimer: I am not an expert in `vector`'s stream fusion, so the thoughts above may not be entirely founded in reality.)

**Comment by cartazio** [comment]
so, as Ryan Says, the code in Vector doesn't have a correctness issue as such from this fusion rule. 

looking at it another way, 
1) Vector kinda uses Monads generally as a sequencing/ordering of evaluation tool . so not a problem there

2) most code using PrimMonad  kinda assumes each monadic effect happens exactly once or are Idempotent 

so in summary: not a bug in terms of behavior of Vector / MVector instances as they exist today, though a definite footgun if one were to treat the fusion modules as public apis. 

Ryan: how clever is the GHC RULES engine at detecting duplicated arguments as equal?

**Comment by cartazio** [comment]
(i assume its syntactic)

**Comment by RyanGlScott** [comment]
> how clever is the GHC RULES engine at detecting duplicated arguments as equal?
>
> (i assume its syntactic)

Yes, that appears to be the case, judging from [this bit](https://downloads.haskell.org/~ghc/8.6.5/docs/html/users_guide/glasgow_exts.html#semantics) from the users' guide:

> "GHC currently uses a very simple, syntactic, matching algorithm for matching a rule LHS with an expression."

**Comment by cartazio** [comment]
hrmm, is there any sane way we could identify when / if such rules might fire on hackage? (and or when building a test harness?) 

.... i probably should look at the PR / change set JOACHIM wrote a while ago for testing fusion stuff with vector as a test case, is that relevant?

**Comment by RyanGlScott** [comment]
Actually, it turns out my claim in https://github.com/haskell/vector/issues/252#issuecomment-513329732 was wrong. There is in fact code in the wild that picks an `m` besides `Id`. In fact, this code is found right in `vector` itself:

https://github.com/haskell/vector/blob/65cfe828f5bddf59fd5aaaead96c5ad45ecd7a8d/Data/Vector/Generic.hs#L2103-L2115

Whether one can successfully combine this with `zipWithM` to drop side effects is unclear to me, but the potential is present, at least.

**Comment by cartazio** [comment]
@RyanGlScott I"ll do a mini hackage grep on a local copy this evening, I think that should still be fine, probably :)

**Comment by gksato** [comment]
I didn't have time to revisit here for a while. Now I've looked through the thread and I'm at a loss what you two are talking about. Are you two talking about inconsistencies that may occur while using the usual `Vector` modules? Or could you be talking about incorrect rewriting that may happen when `Fusion` modules are accessed from other packages? I'm asking this because I have thought that there is *obviously* no problem if packages other than `vector` itself do not call `Fusion` packages.

**Comment by gksato** [comment]
It is annoying to have an ugly incorrect rule in there, though ;)

**Comment by RyanGlScott** [comment]
> Or could you be talking about incorrect rewriting that may happen when Fusion modules are accessed from other packages?

That's the hypothesis I'm running with. There is a minuscule (but realistic) chance that someone might be running `Bundle`/`Fusion` code with an `m` like `IO`, especially given the existence of a specialization for `IO`. I did search through Hackage [here](https://codesearch.aelve.com/haskell/search?query=Bundle%20IO&insensitive=off&space=off&precise=on&sources=on) and didn't find anything incriminating under the phrase "`Bundle IO`", with the exception of `unstreamPrimM_IO` (as I noted above). That is far from an exhaustive search, however.

**Comment by gksato** [comment]
> especially given the existence of a specialization for `IO`.
You mean `unstreamPrimM_IO` ?

**Comment by RyanGlScott** [comment]
> You mean `unstreamPrimM_IO` ?

That, and the `unstreamM[IO]` rewrite rule that uses it. That was likely added for _some_ reason, but I don't know what.

**Comment by gksato** [comment]
I'm sure it's there since `unstreamM` is slow.

**Comment by cartazio** [comment]
Slow in the sense that of dictionary passing and the binds not being
optimized into strict effect ordering lets that become register updates?
Absolutely!  The cost of generics  ;)


We should think about inspection testing or something so we can actually
maintain the invariant that every rewrite rule has at least one example we
can tickle under an o1 or o2 optimizing build.

**Comment by gksato** [comment]
Not *that* way. `unstreamM` goes through the input stream and dumps the result in a thunk for a *list* first, then construct a pure stream from that list. This is slow in that way that `Data.List.mapM` is. 

I haven't actually tested this yet, but I expect that `unstreamPrimM` is rather fast since it can collect result on the way, while it's reading through the stream.

**Comment by cartazio** [comment]
so https://github.com/haskell/vector/blob/65cfe828f5bddf59fd5aaaead96c5ad45ecd7a8d/Data/Vector/Generic/Mutable.hs#L314-L370 
is whats going on underneath 
`unstreamPrimM s = M.munstream s >>= unsafeFreeze`


on the flip side: 
```
unstream :: Vector v a => Bundle v a -> v a
{-# INLINE unstream #-}
unstream s = new (New.unstream s)
```

on the other hand, a lot of the rewrite rules in the vector package are sort of cancellation laws for stream/unstream! https://github.com/haskell/vector/blob/65cfe828f5bddf59fd5aaaead96c5ad45ecd7a8d/Data/Vector/Generic.hs#L2069-L2089

**Comment by cartazio** [comment]
at a certain level, the question becomes:

1) what fraction of fusion opportunities addressable with the stream fusion framework are we achieving? (aka, those that we achieve statically vs some just in time opimtization runtime framework)

2) what fraction of peak throughput in a problem is achievable with the fusion framework on various classes of problems? (aka, what is the performance impact of missed opportunities)

3) can we update/improve the fusion framework to use more recent ideas: eg @amosr and @benl23x5 wrote a neat paper http://benl.ouroborus.net/papers/2017-merges/merges-PPDP2017-final.pdf which gives a bigger space of fusible programs, could we evolve vector to use it underneath? 

one possibly relevant remark at the end of that paper is `When
streams are used multiple times this causes excessive inlining, which
duplicates work. This can change the semantics for effectful stream`

in our context, perhaps the origin of the `zipM` rule in question is a battle against inlining?

**Comment by cartazio** [comment]
https://github.com/amosr/folderol is the code and proofs associated with that paper

**Comment by lehins** [comment]
I am actually starting to use `Stream`s from `vector` directly for a project of mine and this rule can potentially affect my work.
> There is a minuscule (but realistic) chance that someone might be running Bundle/Fusion code with an m like IO

It is really a bug, and despite that it can give some performance improvements in a non-monadic setting, it should not be specified for streams. Perhaps writing up a rewrite rule for `Vector` and `zipWith` instead would be a better choice.

Here is a concrete example that shows how this rule can break pure code. Could be probably simplified even more, but it is good enough I think:

```haskell
module Main where

import Data.STRef
import Control.Monad (when)
import Control.Monad.ST
import qualified Data.Vector.Fusion.Stream.Monadic as S
import Data.Vector.Fusion.Util
import System.Environment

countEvensST :: STRef s Int -> S.Stream Id Int -> ST s (S.Stream (ST s) Int)
countEvensST ref (S.Stream step s) = pure $ S.Stream step' s
  where
    step' t =
      case unId (step t) of
        S.Yield x t' -> do
          when (even x) $ modifySTRef' ref (+ 1)
          pure $ S.Yield x t'
        S.Skip t' -> pure $ S.Skip t'
        S.Done -> pure S.Done

countEvensTwiceST :: S.Stream Id Int -> ST s (Int, Int)
countEvensTwiceST stream = do
  ref <- newSTRef 0
  streamST <- countEvensST ref stream
  pureCount <- S.foldl (+) 0 $ S.zipWithM countEvensPure streamST streamST
  stCount <- readSTRef ref
  pure (stCount, pureCount)

countEvensPure :: Monad m => Int -> Int -> m Int
countEvensPure x y
  | even x && even y = pure 2
  | even x = pure 1
  | even y = pure 1
  | otherwise = pure 0

countEvensTwice :: S.Stream Id Int -> (Int, Int)
countEvensTwice str = runST $ countEvensTwiceST str

main :: IO ()
main = do
  [n] <- fmap read <$> getArgs
  print $ countEvensTwice $ S.generate n id
```

Running above pure code with optimizations and without produces different result, which is no bueno:

```shell
$ ghc -O0 Main.hs 
[1 of 1] Compiling Main             ( Main.hs, Main.o )
Linking Main ...
$ ./Main 20
(20,20)
$ ghc -O1 Main.hs 
$ ./Main 20
(10,20)
```

**Comment by gksato** [comment]
Uh-huh... Nice example.
I've been in wonder if it makes any sense to apply `zipWithM` to monadic streams which are not the lifts of pure streams. However, it *does* make sense if the applied action is commutative with the actions in the stream.

**Comment by cartazio** [comment]
can we easily / sanely write a more specific matching rewrite rule that only works on the pure code and doesn't risk regressing any extant  vector code fusions?

@lehins I empathize, but could you expand on why you're using the vector stream fusion framework here? the repa family of fusion designs and more recent work by related folks seems more robust/powerful/useful for your massiv pkg https://github.com/lehins/massiv/commit/ee9721d77217150e9fd4469e5aae8230bf416ca3  in https://github.com/lehins/massiv/commits/v4.1 is the relevant commit  i assume?

**Comment by cartazio** [comment]
i agree that *if* the fusion tools in vector are "public" apis, its definitely a bug, but I really want to understand what/if any code in the while would be impacted by removing the rewrite rule without making sure we have a pure rule that works on extant code correctly (and would that suffice to doing the correct simplification sthat users may implicitly depend on )

**Comment by lehins** [comment]
@cartazio That's right, repa style fusion is one of the features in `massiv`, but adding streamed arrays as another feature to massiv I can now also do filtering and unfolding of 1D arrays. Another very important consequence of this is the fact that I can now control the streams manually, without relying on the rewrite rules of `vector` package, which are pretty easy to break. For example wrapping any vector with `newtype` will yield vector fusion useless. One more feature I am planning on adding while using vector streams is ability to filter in parallel, but was not too successful yet in getting good performance out my first attempts, so will have to do it a bit later.

I am currently not using streams with ST or IO, so the bug mentioned in this ticket doesn't affect me, but even if I had to use `zipWithM`, I could just reimplement that function myself as a workaround it.

I think having Stream,  Bundle etc. available as public API is a great idea, those very powerful concepts. Not only that they are useful on their own, as I am now finding out, they allow tapping into vector fusion directly, in case someone would like to implement functionality that isn't available for `Vector`s.

I think we could write a safe version of rule like the one discussed in this ticket, but only for `Vector`s directly, or for streams, but restricted to `Id` monad.
> can we easily / sanely write a more specific matching rewrite rule

**Comment by lehins** [comment]
Alternatively an internal `zipWithInternalM = zipWithM` could be written, that is used within vector and has a rule specified on:
```
{-# RULES

"zipWithInternalM xs xs [Vector.Stream]" forall f xs.
  zipWithInternalM f xs xs = mapM (\x -> f x x) xs   #-}
```

**Comment by Shimuuar** [comment]
To summarize discussion so far. Rule in question is wrong and could result in miscompilation. 

However let look how could it be triggered from vector code. Only version from Bundle is used:
```haskell
zipWithM :: (Monad m, Vector v a, Vector v b, Vector v c)
         => (a -> b -> m c) -> v a -> v b -> m (v c)
zipWithM f = \as bs -> unstreamM $ Bundle.zipWithM f (stream as) (stream bs)
```
Which is in turn is defined as:
```haskell
zipWithM :: Monad m => (a -> b -> m c) -> Bundle v a -> Bundle v b -> M.Bundle m v c
zipWithM f as bs = M.zipWithM f (lift as) (lift bs)
```
In vector monadic bundle zipWithM is always called with pure streams. I think we can define rule for  Data.Vector.Fusion.Bundle.zipWithM where it's perfectly safe instead of monadic bundles
