### ISSUE TITLE
Data.Vector.Generic.eqBy is suboptimal for vectors of known size

### ISSUE THREAD

**Issue by sjakobi** [haskell/vector#260]
For e.g. `Data.Vector.Vector`, the first step should be to compare the lengths, which `Data.Vector.Generic.eqBy` doesn't seem to do. So `Data.Vector` should probably get a custom `eqBy`.

**Comment by cartazio** [comment]
Good catch!

Why don’t we just change the genrric one ?  Else duplicated code!

**Comment by sjakobi** [comment]
> Why don’t we just change the genrric one ?

Sure! I don't understand the current implementation, with fusion etc., so I hope someone else steps up and provides a patch! :)

**Comment by cartazio** [comment]
i think step zero is to write eqBy for streams! (i mean bundles :))
for streams, when the sizes are known, you can definitely do the fast
failure mode :)

http://hackage.haskell.org/package/vector-0.12.0.3/docs/Data-Vector-Fusion-Bundle-Monadic.html
notice the size field!
