### ISSUE TITLE
Missing API master issue

### ISSUE THREAD

**Issue by merijn** [haskell/vector#262]
This issue is to document functions that are in *some* of the vector modules, but not others. I will update and add missing functions as I find them:

Not anywhere, but nice to have:
  - `iforM`
  - `iforM_`

Mutable modules should probably re-export `PrimState` and `PrimMonad` so it's easier to write `PrimMonad` generic code without adding the additional `primitive` dependency and an extra import.

`Data.Vector.Storable`:
  - `imapM`
  - `imapM_`

**Comment by cartazio** [comment]
yay, thx! this sort of concrete actionable feedback is really helpful!

theres some tools somewhere for doing haddock or .hi file based api diffs,
something like that would be super helpful to sanity check cleanup vector
with

**Comment by merijn** [comment]
Right now I'm just writing down everything I'm having to reimplement to get my stuff working >.>
A substantial number are already in `Data.Vector.Generic`, so I'm unsure why they aren't exported already.

**Comment by merijn** [comment]
Various monadic folds:

- `foldM`
- `ifoldM`

I suppose only strict left folds are sensible here?

**Comment by cartazio** [comment]
Not necessarily.  In terms of stream fusion yes, but for materialized
vectors both are valid.

**Comment by Shimuuar** [comment]
This leaves only

> Mutable modules should probably re-export PrimState and PrimMonad so it's easier to write PrimMonad generic code without adding the additional primitive dependency and an extra import.

I think it's fair request and won't cause name clashes since module is expected to imported qualified
