### ISSUE TITLE
enumFromTo fails QC at -O2

### ISSUE THREAD

**Issue by paniag** [haskell/vector#268]
`$ ghc --version`
`The Glorious Glasgow Haskell Compilation System, version 8.6.5`
`$ cabal --version`
`cabal-install version 3.0.0.0`
`compiled using version 3.0.0.0 of the Cabal library`

Repro:
`$ cabal get vector`
`$ cd vector-0.12.0.3`
`$ echo "packages: vector.cabal" > cabal.project`
`$ cabal configure --disable-benchmarks --enable-tests && cabal install --only-dep`
`$ cabal test`

[vector-0.12.0.3-vector-tests-O2.log](https://github.com/haskell/vector/files/4088935/vector-0.12.0.3-vector-tests-O2.log)

**Comment by cartazio** [comment]
thanks! 
Ok, it looks like the vector specialization/enumfromto rule for Double is wrong! eeek

**Comment by cartazio** [comment]
@amosr eek, the bad enumfromto strikes again!

**Comment by cartazio** [comment]
@nomeata fyi: nasty rules bug living here :)

**Comment by paniag** [comment]
O0 passed (chance?)
Running O1 now.

[vector-0.12.0.3-vector-tests-O0.log](https://github.com/haskell/vector/files/4088949/vector-0.12.0.3-vector-tests-O0.log)

**Comment by cartazio** [comment]
```
module Main where

import qualified MyLib (someFunc)
import qualified Data.Vector as V
main :: IO ()
main = do
  print ( V.fromList (enumFromTo 6.511955808615705e-2 18.451281790142502) == (V.enumFromTo 6.511955808615705e-2 18.451281790142502) )
 ```
outputs false on O1 :(

**Comment by cartazio** [comment]
based upon the output from  ` ghc-options: -O1  -ddump-rule-firings`
i'm going to say 
```
    enumFromTo<Double> [Bundle] (Data.Vector.Fusion.Bundle.Monadic)
```
is the culprit. I'm not sure why this wasn't exposed before in the CI ...

**Comment by paniag** [comment]
-O1 predictably failed too.

[vector-0.12.0.3-vector-tests-O1.log](https://github.com/haskell/vector/files/4089002/vector-0.12.0.3-vector-tests-O1.log)

**Comment by Shimuuar** [comment]
#188 is certainly related

**Comment by Shimuuar** [comment]
I dug a little deeper. Failure is due to some subtle difference in how enumFromTo is implemented.

```haskell
import qualified Data.Vector as V
import Numeric.MathFunctions.Comparison

main :: IO ()
main = mapM_ print
  [ (x,y, ulpDelta x y)
  | (x,y) <- enumFromTo a b `zip` V.toList (V.enumFromTo a b)
  ]

a,b :: Double
a = 6.511955808615705e-2
b = 18.451281790142502
```

produces following output

```
(6.511955808615705e-2,6.511955808615705e-2,0)
(1.065119558086157,1.065119558086157,0)
(2.065119558086157,2.065119558086157,0)
(3.065119558086157,3.065119558086157,0)
(4.065119558086157,4.065119558086157,0)
(5.065119558086157,5.065119558086157,0)
(6.065119558086157,6.065119558086157,0)
(7.065119558086157,7.065119558086157,0)
(8.065119558086158,8.065119558086156,-1)
(9.065119558086158,9.065119558086156,-1)
(10.065119558086158,10.065119558086156,-1)
(11.065119558086158,11.065119558086156,-1)
(12.065119558086158,12.065119558086156,-1)
(13.065119558086158,13.065119558086156,-1)
(14.065119558086158,14.065119558086156,-1)
(15.065119558086158,15.065119558086156,-1)
(16.065119558086156,16.065119558086156,0)
(17.065119558086156,17.065119558086156,0)
(18.065119558086156,18.065119558086156,0)
```

Note that difference is 1 ulp! That is implementations are almost the same.

**Comment by cartazio** [comment]
1ulp!  Egads.  Is this one of those cases where reassociatting the math
will get them to agree ?


That small a discrepancy does make it less terrible as bugs go.  But still
pretty bad from a program semantics preserving optimization perspective.

Thank you very much for distilling this down!

I’d like to backport whatever fix plus include it in the next release.  Do
you wanna have a go at a pr patch ?

**Comment by Shimuuar** [comment]
Here is answer: vector computes `enumFromTo a` as `iterate (+1) a` and  base as `(+1) <$> iterate (+1) 0`!

But I'm afraid this is not the end. Tests fail very reliably for me. So I suspect that base changed implementation at some point so enumFromTo _used_ to be correct.

**Comment by cartazio** [comment]
That’s bad. Maybe one of the fusion rules I base is wrong ?

**Comment by Shimuuar** [comment]
Yes! They did: https://gitlab.haskell.org/ghc/ghc/commit/4ffaf4b67773af4c72d92bb8b6c87b1a7d34ac0f That was a deliberate change motivated by numerical stability (Corresponding issue: https://gitlab.haskell.org/ghc/ghc/issues/15081 )

**Comment by Shimuuar** [comment]
Change is relatively recent GHC8.4 (base-4.11) used old definition https://hackage.haskell.org/package/base-4.11.0.0/docs/src/GHC.Real.html#numericEnumFrom

GHC8.6 (base-4.12) uses new one: https://hackage.haskell.org/package/base-4.12.0.0/docs/src/GHC.Real.html#numericEnumFrom

**Comment by Shimuuar** [comment]
Confirm. Tests always pass for GHC8.4 and always fail for GHC86 after only a few tests. So fix will have to include CPP for different base versions.

**Comment by cartazio** [comment]
Or we need to open a ticket about this on ghc.  If you’re in the groove
it’d be good to do that.  This was a semantic change to a core library,
base.

**Comment by cartazio** [comment]
Grrr.  Maybe accommodating this is the right approach. I’m afk for another
hour or so atm.thank you for getting to the bottom of this

**Comment by cartazio** [comment]
This does suggest we should have another test suite that just makes sure
that the internal specislziations are exposed to ci.  I was kinda thinking
about that before but this kinda grounds that a big sanity check

**Comment by Shimuuar** [comment]
I think "What have been released couldn't be unrelerased", so vector has to accommodate that change in order to preserve optimization validity. I think I'll make a PR to fix this problem

**Comment by cartazio** [comment]
Fixed, thanks to all involved!
