### ISSUE TITLE
figure out how to thread checking information along fusion transformations

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#281]
per chat with @lehins  on https://github.com/haskell/vector/pull/279 and related tickets around bound checking vs fusion rules.

**Comment by cartazio** [comment]
currently, not enough information is threaded around during `RULES` transformation to allow fusion and bounds checking!

**Comment by cartazio** [comment]
per https://github.com/haskell/vector/issues/257

**Comment by Shimuuar** [comment]
Both linked issues are resolved and it's not clear and it's not clear what is proposed course of action. Closing
