### ISSUE TITLE
Fusion of `take` can cause OutOfMemory

### ISSUE THREAD

**Issue by lehins** [haskell/vector#282]
Here is a simple repro:

```haskell
import qualified Data.Vector.Primitive as V -- or any other for that matter

main = do
  let xs = [1, 2, 3, 4, 5] :: [Int]
  print $ V.take (maxBound `div` 8) $ V.fromList xs
```
Results in out of memory:

```
$ stack exec -- ghc take.hs -O1 -fforce-recomp && ./take
[1 of 1] Compiling Main             ( take.hs, take.o )
Linking take ...
take: Out of memory
```

Same thing as it was observed with `slice` in #257 and fixed in #279, except I think we can fix this issue without giving up fusion of `take` function.

The actual cause for this is that after a few rewrite rules we get into a situation where a smaller size being selected: https://github.com/haskell/vector/blob/f0cf694ec6feaae97f08035eefcf0c7ec76931cc/Data/Vector/Fusion/Bundle/Monadic.hs#L269-L272

and between `Unknown` and `Exact maxBound` ironically the smaller one is `Max maxBound` :)

```haskell
>>> smaller (Exact maxBound) Unknown
Max 9223372036854775807
```

Which later simply causes the out of memory when `vmunstreamMax` tries to allocate too much.

_Side note_ - `V.take maxBound $ V.fromList xs` is guarded by `basicUnsafeNew` up to `div maxBound (sizeOf (undefined :: e))`, but not for smaller than than and no guards for boxed vector.

**Comment by cartazio** [comment]
`smaller` isn't sound it ... sounds like

**Comment by lehins** [comment]
Correct. It is sound in other place it is used, namely in with `zipWithM`, but not for `take`

**Comment by cartazio** [comment]
like, this is meant as "compute the greatest definitely true upper bound on size", and here if either thing is unknown, the bound is unknown. right?

**Comment by cartazio** [comment]
*smallest true upper bound

**Comment by lehins** [comment]
This is what we want for `drop`:
https://github.com/haskell/vector/blob/18a615e261ed655be0c2f0c888e73c561b0ba639/Data/Vector/Fusion/Bundle/Size.hs#L94-L99

**Comment by cartazio** [comment]
to be clear: this only applies to take, not to drop? i got a tad confused at one point

**Comment by lehins** [comment]
That is correct, `drop` doesn't care about its `Int` argument that much :)
