### ISSUE TITLE
how to best fix a bad commit body

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#284]
@hvr 

```
Fix specialized versions for Bundle.enumFromTo

If upper bound is maxBound sep function will overflow and continue to fill
vector past end of a vector. Fix is only partial since Stream is affected by
same problem
```

we forgot to change the description to say it cleans up both stream and bundle, any good way to do that or is reality poisoned? (doesn't matter too much, but still pretty annoying mistake on my part since i noticed this originally)

**Comment by cartazio** [comment]
to be clear, in master

**Comment by lehins** [comment]
You can't do it without rewriting git history, which is a bad idea to do on `master`.

**Comment by cartazio** [comment]
i know, but theres still timeeee

**Comment by cartazio** [comment]
oh well,

**Comment by cartazio** [comment]
i could delete master and push it back ;)

**Comment by cartazio** [comment]
im 95% joking

**Comment by cartazio** [comment]
also this is exactly why collab code review AND checking we like the commit messages is so important

**Comment by cartazio** [comment]
well, i guess we need to close this issue and just cry inside :)
