### ISSUE TITLE
v0.12.1.2 release candidate 

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#294]
commit 02138dfef74427555764c95534e6f565baa22eb2 as 0.12.1.2 release 

https://hackage.haskell.org/package/vector-0.12.1.2/candidate for the tarball url 
tarball url https://hackage.haskell.org/package/vector-0.12.1.2/candidate/vector-0.12.1.2.tar.gz

 shasum -a512 dist-newstyle/sdist/vector-0.12.1.2.tar.gz
36d0237cf7c5a6b78f88b33ff09ea8b19baeaf85609efdeba9ab802ca588956457d4607304b73e8d58e9e802a9101c23da62caee71508f069047a6d531e50170  dist-newstyle/sdist/vector-0.12.1.2.tar.gz

sanity check: can different people get the same sdist hash from generating it themselves? :)

**Comment by cartazio** [comment]
cc @lehins @Shimuuar  :)

**Comment by cartazio** [comment]
https://travis-ci.org/haskell/vector/builds/644867208

**Comment by Shimuuar** [comment]
Yep. I got same hash for tarball

**Comment by cartazio** [comment]
for the one you downloaded or the one you generate locally? :)

**Comment by Shimuuar** [comment]
For one generated locally of course

**Comment by lehins** [comment]
Sorry @cartazio I don't use cabal so I won't be able to recreate the same sdist as you ;)

Here is a downloaded one:
```
$ curl -s https://hackage.haskell.org/package/vector-0.12.1.2/candidate/vector-0.12.1.2.tar.gz | sha512sum 
36d0237cf7c5a6b78f88b33ff09ea8b19baeaf85609efdeba9ab802ca588956457d4607304b73e8d58e9e802a9101c23da62caee71508f069047a6d531e50170  -
```

**Comment by cartazio** [comment]
since the haskell org travis is busy with cabal atm, https://travis-ci.org/cartazio/vector/builds/644871852 might run faster

**Comment by cartazio** [comment]
GREEN. pushign tag, confirming my SDIST generates the same hash
then publishing

**Comment by cartazio** [comment]
published!
killing .1

**Comment by cartazio** [comment]
base < 0  constraint now on .0 and .1 releases

**Comment by lehins** [comment]
@cartazio I don't think you need to be that harsh and make them unbuildable, what I meant was to mark these version as deprecated on hackage: `0.12.1.0`, `0.12.1.1`. This would make all the tools such as `cabal` and `stack` not to use them, but if someone is really eager they can still build those versions.

In any case, please mark this two versions as deprecated on hackage, otherwise it is not obvious that they cannot (should not) be used.

**Comment by cartazio** [comment]
updated the deprecation flags. (thx for reminding me )
poisoning the constraint info means that no user gets subtle bugs when doing various thigns :)

**Comment by lehins** [comment]
Sure, I don't have a strong opinion about poisoning deprecated versions.
