### ISSUE TITLE
iterateN's documentation disagrees with its behaviour

### ISSUE THREAD

**Issue by kozross** [haskell/vector#303]
The [documentation][1] for ``iterateN`` states:

> Apply function n times to value.

However, its behaviour disagrees with this, as the function is applied _max{n - 1, 0}_ times, not _n_ times:

```
> import Data.Vector as V
V> V.iterateN 5 succ (0 :: Int)
[0,1,2,3,4]
V> V.iterateN 0 succ (0 :: Int)
[]
V> V.iterateN 1 succ (0 :: Int)
[0]
```

This is clearly incorrect documentation, and is actually quite confusing - its description suggests the length of the resulting vector should be _n + 1_.

[1]: http://hackage.haskell.org/package/vector-0.12.1.2/docs/Data-Vector.html#v:iterateN

**Comment by Kleidukos** [comment]
ping @cartazio. Do you want me to open a PR?

**Comment by cartazio** [comment]
hrm 

```haskell
-- | Apply monadic function n times to value. Zeroth element is original value.
iterateNM :: Monad m => Int -> (a -> m a) -> a -> Bundle m u a
{-# INLINE_FUSED iterateNM #-}
iterateNM n f x0 = fromStream (S.iterateNM n f x0) (Exact (delay_inline max n 0))

-- | Apply function n times to value. Zeroth element is original value.
iterateN :: Monad m => Int -> (a -> a) -> a -> Bundle m u a
{-# INLINE_FUSED iterateN #-}
iterateN n f x0 = iterateNM n (return . f) x0

-- Scans
```

is this a documentation bug or an implementation bug!  hrmmm

**Comment by Kleidukos** [comment]
@Shimuuar Hi! I think you're the one who introduced this function in https://github.com/haskell/vector/commit/82fb7c22ef5fd46b5f4c1e3d88af84d263e4d518 ? Can you remember what was the original / intended behaviour? :)

**Comment by cartazio** [comment]
Woah the original commit has mutually conflicting docs. Hrmmm

**Comment by Kleidukos** [comment]
I don't know the codebase very well. Were tests ever added for this function @cartazio?

**Comment by Shimuuar** [comment]
> Can you remember what was the original / intended behaviour? :)

AFAIR code is correct and documentation is wrong. Sadly GHC doesn't proofread haddock. In any case I think it's too late to change function semantics so haddock should be corrected. On top of that `iterateN size_of_vector` is consistent with all other `whateverN` functions

**Comment by Kleidukos** [comment]
Great, thank you very much! :)  
@kozross since you opened the issue, do you want to open a PR? I can do it if you don't have the bandwidth right now.

**Comment by cartazio** [comment]
hrmmm, is the the correct end state? like, should1 iterateN n f a == V.FromList $ take n (iterate f a)1 or should it be 1== V.FromList $ take (n+1) (iterate f a)1

**Comment by cartazio** [comment]
`iterateN n f a == V.FromList $ take n (iterate f a)` or should it be `== V.FromList $ take (n+1) (iterate f a)`

**Comment by cartazio** [comment]
whats mroe "natural"?

**Comment by cartazio** [comment]
i suppose (max 0 (n+1))

**Comment by Shimuuar** [comment]
replicate/generate/unfodrN all take Int parameter as result's size (upper limit of size) so for sake of consistency iterate should use parameter as size (current code behavior) 

Most importantly we shouldn't change code behavior for no compelling reason. It was this way for 9 years after all and no one complained. I think we should just fix haddocks

**Comment by cartazio** [comment]
true :)

**Comment by kozross** [comment]
If it's a doc change, I can probably PR it. Will try to do that today.

**Comment by cartazio** [comment]
Do the doc pr please. Semantics move slower
