### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by chessai** [haskell/vector#310]
Hi @lehins @Shimuuar, 

I'm very excited about all the works that's already been done in the last 48 hours on vector. I just have two thoughts for your consideration right now.

1. There are a large number of old vector issues dating back to 2014, that have never been worked on/may have been worked on and just never closed (I think that most fall into the former category). I think this sends a very bad message to the community, that things are stagnating and never getting fixed. Obviously you both know all this, and just started working on things, but I think perhaps older issues may be good to prioritise over new ones. Of course, if you think a newer issue takes precedence over an older one, that's just fine as well. I'm not going to dictate you on how you prioritise issues; this is just a suggestion.

2. I feel that two maintainers outside of the CLC is not enough. The number of libraries the CLC oversees is going to expand soon (bytestring, text, unordered-containers, etc.), and it's under-manned. Perhaps more maintainers will arise organically, but if you know of anyone who may be a good fit and is interested, please let me/them know. We don't want to have too many maintainers (things can stall), but too few means higher rate of failure/burnout (people have lives and jobs!). I will be fielding for people to help maintain vector (as well as other core libraries) over the coming weeks.

Thanks again for all the work you're doing!

**Comment by Bodigrim** [comment]
@chessai I already talked to @lehins and intend to join forces with him and @Shimuuar

**Comment by chessai** [comment]
@Bodigrim awesome! I think you would be a great maintainer.

**Comment by chessai** [comment]
@Bodigrim I have granted you push permissions on vector. Excited to have you!

**Comment by lehins** [comment]
@chessai 100% onboard with everything you said here. Also glad to have @Bodigrim joining us!

**Comment by Shimuuar** [comment]
> There are a large number of old vector issues dating back to 2014, that have never been worked on/may have been worked on and just never closed

I went through issues and I think I closed everything that could be closed outright. Right now I want to merge PR that could be merged. 5 year old issue may look as problem but "accepted" PR that is open for a year just screams "unmaintained!".

> I feel that two maintainers outside of the CLC is not enough.

I agree. Welcome @Bodigrim!

**Comment by chessai** [comment]
Closing this issue, since everyone has seen it.
