### ISSUE TITLE
Make a minor release: vector-0.12.2.0

### ISSUE THREAD

**Issue by phadej** [haskell/vector#346]
For example I need `unstreamM` a PR of exporting which was merged in February last year.

**Comment by Shimuuar** [comment]
@lehins @Bodigrim I think we all agree that we need to make release. This issue seems like a good place for preparing 0.13. I'll look through issues over the weekend to pick ones that _should_ be included into release. I think it's good idea to release all breaking changes at once

**Comment by lehins** [comment]
@Shimuuar 100% on board. Let me know if you need any help. I'll try to look through outstanding tickets as well and see if there is anything else worth implementing that requires breakage for the new major release.

One thing I do want to make sure is that the new version works with new upcoming ghc-9.0
haskell/primitive#296 has some compatibility problems, which probably won't affect vector directly, but we might not be able to confirm that vector is compatible until `primitive` is made compatible.

**Comment by phadej** [comment]
https://gitlab.haskell.org/ghc/head.hackage is an infrastructure to test against bleeding edge GHC (and have a patch for `primitive`).

**Comment by lehins** [comment]
@Shimuuar I do agree that we need a new major release soon, but after looking through the current trunk I don't we have enough changes to justify a new breaking release. Here is my though process: 

* We'll first fix issues that affect security and are indeed bugs that are dangerous: at least #118 and #301
* I will cherry pick all non-breaking changes from master into a feature branch `vector-0.12.2.0` and make a release
* Within the next month or two we tackle and combine as much of the stuff as possible that is indeed breaking. So far we only have roles, drop ghc support for < 7.10 , `MonadFIx` instance and `maximumBy` stuff (let me know if I missed anything). 

I'll go through all tickets one-by-one tomorrow and see what's feasible.

CC @Bodigrim How do you feel about the next major/minor release?

**Comment by Shimuuar** [comment]
I think #335 (not merged yet) alone justify 0.13. Just to be clear. What I meant by "preparing a release" is to decide what should be included into 0.13 and could be implemented reasonably fast (month or so).

I have no objection to 0.12.2.0 though

**Comment by Bodigrim** [comment]
> drop ghc support for < 7.10

AFAIU this does not qualify as breaking: no existing build can be broken by this. It will be an unnecessary challenge to cherry-pick everything, while keeping compatibility with old GHCs. 

> How do you feel about the next major/minor release?

My preference is to focus efforts on a major release in a couple of months. But if someone has energy to spare for cherry-picking and testing `vector-0.12.2.0`, I will not oppose :)

**Comment by phadej** [comment]
If the timescale for next release is two months or more, then please tell so clearly. I could then not wait for it (i.e. copy needed functionality), and e.g. unsubscribe from this issue.

I didn't know that `vector` is in unreleaseable state.

**Comment by Bodigrim** [comment]
@phadej Theoretically we can release immediately as `vector-0.13` and in a month or two - as `vector-0.14`. I just do not believe that ecosystem will be ready to accomodate such rapid changes in succession.

**Comment by phadej** [comment]
I'm *fine* with waiting as far as plan is communicated.

Two major releases is a bad idea. I will purposefully wait until `vector-0.14` is released, so I don't need to go through my packages twice. You are right with "not ready to accomodate such rapid changes".

**Comment by lehins** [comment]
It sounds like we do want `vector-0.12.2.0`, I'll work on that.

> AFAIU this does not qualify as breaking

You are right, it really does not qualify as a breaking change, but we have a moral obligation to our users. I'd personally hate if someone took away ghc support in a minor release.

@phadej Communicating: minor release that will include `unstreamM` will happen in about a week, vector-0.13 however is targeted in a couple of months. Let us know if it is not clear enough. Also, if you'd like to speed the whole process up, feel free to send us some money and we will put some more effort into project management and package maintenance. We are all putting our free time into the project, so If money is not an option then some politeness and appreciation will work great as currency too. What I am trying to say is that you are not our manager and your demanding tone is just not cool.

**Comment by phadej** [comment]
@lehins I'm sorry if I sound demanding, it wasn't my intention.

I'm also maintaining **all of my OSS stuff** on my free time, so knowing what and when is happening (or not) helps to plan that. (Except `Cabal` work, most of which is paid by Well-Typed's client, yet it isn't "my" project.)

I'm sorry for causing bad mood.

**Comment by lehins** [comment]
@phadej Thank you. I really appreciate it.

I'll re-open this ticket, so I can track release of vector-0.12.2 version, if it's ok with you, of course? Feel free to close it again and I'll open a new one otherwise

**Comment by phadej** [comment]
I unsubscribed from this one, so I shouldn't get notifications.

**Comment by lehins** [comment]
I've backported all of the non-breaking changes from master to [`v0.12.2.0-release-branch`](https://github.com/haskell/vector/tree/v0.12.2.0-release-branch), diff can be viewed here:
https://github.com/haskell/vector/compare/v0.12.1.2...v0.12.2.0-release-branch

I'll wait for a few other fixes that are coming this week and will make this minor release next weekend. I've also improved changelog a bit and added bunch of `since` pragmas for all new functions, all of which I'll submit as a PR into master after the release.

**Comment by lehins** [comment]
@Bodigrim and @Shimuuar I'll cut `vector-0.12.2.0` release in a couple of hours, let me know if you find anything I am missing that should have been included (see the diff in my previous comment). Also if you'd like me to hold off for any reason let me know too.

I've added bunch of `@since` haddock pragmas and updated changelog, which I'll port back into master after the release

**Comment by Shimuuar** [comment]
@lehins I looked through the branch. LGTM

**Comment by lehins** [comment]
[`vector-0.12.2.0`](https://hackage.haskell.org/package/vector-0.12.2.0) release is out. 

CC @phadej [`unstreamM`](https://hackage.haskell.org/package/vector-0.12.2.0/docs/Data-Vector-Generic.html#v:unstreamM) is now available :wink:
