### ISSUE TITLE
Why are the release tags on a dangling branch of history

### ISSUE THREAD

**Issue by infinity0** [haskell/vector#379]
Git history looks like this:

~~~~
*   4c87e88 (HEAD -> master, origin/master, origin/HEAD) 2021-04-06 Alexey Kuleshevich       Merge pull request #354 from haskell/350-restructure
|\  
| * a414f96 2021-01-16 Alexey Kuleshevich       Move all vector package related code into it's own directory. Fix #350
|/  
*   c89460b 2021-04-06 Alexey Kuleshevich       Merge pull request #375 from haskell/fixup-due-to-0.12.3.0-release
| 
[..]
|
| * dcfd78f (tag: v0.12.3.0) 2021-04-04 Alexey Kuleshevich       Bump up the version
| |
| * 7397eb8 2021-04-02 Alexey Kuleshevich       Disable CI for older ghc
| |
| [..]
| |
| * 455136f 2020-01-31 Carter Tazio Schonwald   Revert "Fix maximumBy comparison"
| |
| * 0737049 2020-01-31 Carter Tazio Schonwald   revert Role annotations for 0.12.1 branch
|/  
* d9d1d00 2020-01-31 Carter Tazio Schonwald   rename changelog -> changelog.md plus update cabal file
|
* 24ebd34 2020-01-31 Alexey Kuleshevich       Fix selection of the resulting size when `take` is applied: (#286)
[..]
~~~~

Could you explain how development workflow works? How does the master branch relate to the release tags?

**Comment by infinity0** [comment]
Oh never mind, looks like the master branch is for the upcoming version 0.13.

**Comment by lehins** [comment]
All development works on master, just like any other project. If we need to make a release to a version that can have only non-breaking changes (eg, 0.12.x at the moment), only those changes will get backported and a release is cut.

Current master includes a lot of breaking changes, therefore next major release from master will be vector-0.13.0.0, which is not that far away.

In other words most contributors should not worry about release tags and git history outside master.
