### ISSUE TITLE
data rather than newtype for unboxed vectors?

### ISSUE THREAD

**Issue by edsko** [haskell/vector#391]
All of the data type instances for the unboxed vectors are `newtype instance` rather than `data instance`. I was wondering if changing that would have significant downsides? The advantage of changing it to `data` would be that we get a tag on the heap that tells us what kind of vectors we are dealing with, which is occasionally useful for low-level tooling. The obvious cost is one tag per vector, but that is probably not a huge deal? I don't however know how, if at all, this interacts with potential fusion. 

This is not a high priority, of course :)

**Comment by Shimuuar** [comment]
There's performance price. We'll get +2 words per vector (tag + pointer) and extra pointer chase. This couldn't be good for performance. I could have some relevant measurement lying around. 

I suspect that performance  price is too high to make everyone pay it. I don't have benchmarks to prove it. Maybe there's way to make it compiler time feature for ones that need it?..

**Comment by edsko** [comment]
Right, if that cost would be incurred on every element access, that would be bad, for sure. I guess I was kind of hoping that that would not be the case, but yeah, maybe that was overly optimistic.

**Comment by Shimuuar** [comment]
There's agreement that such change won't happen. I'm closing this as WONTFIX
