### ISSUE TITLE
Missing documentation for `Data.Generic.Vector.New`

### ISSUE THREAD

**Issue by konsumlamm** [haskell/vector#403]
The `Data.Generic.Vector.New` module currently has no documentation, other than the module description.

For me, it is kinda obvious what the functions/types are doing (though I'm not sure how to write it down currently, I can try later), but I doubt that's the case for everyone. Doc comments would help nevertheless, they could also show the runtime complexities for example.

**Comment by Shimuuar** [comment]
Fixed by #466
