### ISSUE TITLE
Drop GHC-7 support

### ISSUE THREAD

**Issue by phadej** [haskell/vector#419]
The `Eq1`, `Ord1`, `Show1` and `Read1` instances are defined conditionally, and this bite me.

Either add them across all GHC / `base` versions (from `transformers` or `transformers-compat`) or drop GHC-7 support.

**Comment by lehins** [comment]
Support for ghc-7 has been dropped in #400, so the next release will not have those conditional instances.

**Comment by phadej** [comment]
Great news!
