### ISSUE TITLE
New version vector 0.14?

### ISSUE THREAD

**Issue by Vekhir** [haskell/vector#467]
Hi,
please release a new version of `vector` on Hackage. In particular, I'm affected by issue #460 which is already fixed in main, but the fix is not trivial to port to the 0.13 version available via Hackage. There have been a lot of changes in the past year :)

The improved version bounds for primitive and doctest also don't hurt. A new release would allow the Arch repos to move to more recent versions of the Haskell packages.

Thanks,
-- Vekhir

**Comment by Shimuuar** [comment]
There's weren't any changes that warrant even minor bump. But perhaps it good time to make a patch release. QC compatibility is important for downstream. @lehins @Bodigrim, your opinion?

**Comment by Bodigrim** [comment]
If someone has bandwidth, it would be nice to have a release compatible with GHC HEAD, which requires efcb47594c6157ed34f28254987c7935676d5e84.

I'd suggest to do a minor version bump. Patch releases are for packaging fixes only.

**Comment by lehins** [comment]
> If there's no objections I'll prepare PR with version bump and changelog

@Shimuuar That would be awesome!

**Comment by Vekhir** [comment]
Yeah, the version in the title was a rather ad-hoc suggestion. Really any version bump is fine

**Comment by Bodigrim** [comment]
@Shimuuar could you possibly release `vector-stream` as well? GHC to-be-9.10 requires efcb47594c6157ed34f28254987c7935676d5e84.

**Comment by Shimuuar** [comment]
@Bodigrim I've made #474. Do version bounds on `base` should be bumped as well?

**Comment by Bodigrim** [comment]
> @Bodigrim I've made #474. Do version bounds on `base` should be bumped as well?

Not yet, I’d rather do it later, once `base` is finalized.

**Comment by Shimuuar** [comment]
@Bodigrim I don't have upload rights for `vector-stream`. It seems only @lehins can upload ATM

**Comment by lehins** [comment]
@Shimuuar and @Bodigrim I've added both of you as maintainers to `vector-stream`

**Comment by Shimuuar** [comment]
Thank you! `vector-stream-0.1.0.1` is on hackage. Well I'm closing this issue
