### ISSUE TITLE
Why not add index counterparts to monadic loops in Data.Vector.Unboxed? (imapM, ifoldrM etc.)

### ISSUE THREAD

**Issue by is7s** [haskell/vector#5]
I've found that I need these functions often a lot in practice,. For Data.Vector there functionality can easily be achieved by using sequence or sequence_. However for Data.Vector.Unboxed there's currently no solution except either to implement the loops manually, which is very un-idiomatic, or to convert to Data.Vector. Is it possible that functions like imapM_, ifoldr etc. be provided, for Data.Vector.Unboxed at least?

**Comment by cartazio** [comment]
I think this got merged in a while ago :) 
(though some bugs may have snuck through)
