### ISSUE TITLE
Support GHC 9.12

### ISSUE THREAD

**Issue by andreasabel** [haskell/vector#509]
> [__5] rejecting: base-4.21.0.0/installed-cc73 (conflict: vector => base>=4.9 && <4.21)

**Comment by Shimuuar** [comment]
I tested vector locally with GHC9.12.1-alpha1 both master and both `vector-0.13.1.0` and `vector-stream-0.1.0.1`. Both work fine so I bumped upper limit on base on hackage. `primitive` and test dependencies need bump too but that's another problem

**Comment by andreasabel** [comment]
Thanks @Shimuuar!
