### ISSUE TITLE
Document that `force` always copies

### ISSUE THREAD

**Issue by jorisdral** [haskell/vector#511]
The haddocks of the `force` function mentions that the input vector is *possibly* copied into a new return vector.

![image](https://github.com/user-attachments/assets/30eaa18f-f7d7-45f5-8e5c-efa5fb07119b)

It seems however that `force` *always* copies regardless of the vector type, because the implementation for each vector type calls `Data.Vector.Generic.force`, which uses `basicUnsafeCopy`. 

If my understanding is correct, should the haddocks be updated to specify that the function always copies?

**Comment by Shimuuar** [comment]
It's poorly worded. `force` always creates copy except when optimized is able to elide that copy. Specifically after using slice it will perform copy. 

On the other hand output in some very special cases there're rules that could elide that copy. `force (generate 10 f)`.
