### ISSUE TITLE
FYI: cabal-install will always solve for tasty too

### ISSUE THREAD

**Issue by phadej** [haskell/vector#519]
Due `vector` having a (private) library for benchmarks, `cabal-install`'s solver will always also solve for its dependencies, even if the library is never required.

This is not really an issue, but it's confusing when someone (like me) looks at the install plan and wonders why e.g. `tasty` appears there.

This is long-standing issue in `cabal-install` https://github.com/haskell/cabal/issues/4087

EDIT: the worst case scenario is that this can lead to dependency loop between packages (but not components). Likely `tasty` is dependency-lightweight package itself.

**Comment by lehins** [comment]
Thank you for letting us know. I personally was familiar with this issue. Seems like more reason to solve it in `cabal`. There will be more and more packages using private and public sub-libraries and it seems like a serious deficiency in a build tool that claims to have full support of this feature.
