### ISSUE TITLE
Support for Safe Haskell

### ISSUE THREAD

**Issue by yav** [haskell/vector#56]
Hello,

would it be possible to add support for Safe Haskell?  I imagine that a lot of the library is Safe, or at least Trustworthy,  but none of the modules appear to be marked as such. 

-Iavor

**Comment by Zemyla** [comment]
What about specific Data.Vector.???.Safe modules, marked as Trustworthy, that only reexport safe methods?

**Comment by cartazio** [comment]
it probably makes the most sense to just mark vector as trust worthy wholesale. Honestly no part of vector is truly safe unless you build with bounds checks enabled :)

**Comment by Shimuuar** [comment]
But since vector export unsafe* functions it's not exactly trustworthy.

**Comment by cartazio** [comment]
true :)
in some sense, the only way to make it trustworthy would be to add bounds checks to all the unsafe code, right?

**Comment by dolio** [comment]
Yeah, I'm not wild about marking vector trustworthy.

I think what might be best is to separate out Unsafe modules, which contain unsafeFoo. Those are marked unsafe. Then the normal modules could export just the things that do bounds checking, and can be declared trustworthy.

I'm actually not a great fan of unsafeFoo vs. foo. But I guess I'll create a new ticket to talk about that issue.

**Comment by Shimuuar** [comment]
I propose to close this as wontfix for following reasons:

 1. vector exports a lot of memory unsafe functions
 2. History of bugs (#188, #257) shows that even safe functions aren't all that safe
 3. Safe extension didn't get much traction

**Comment by chessai** [comment]
I'm onboard with @Shimuuar here, for all the same reasons.

**Comment by cartazio** [comment]
Plus safe mode disables any form of rules based optimization.

**Comment by chessai** [comment]
Closing. Anyone feel free to reopen if a new argument arises for needing this.
