### ISSUE TITLE
Failure in fusion leads to very inefficient code

### ISSUE THREAD

**Issue by takano-akio** [haskell/vector#59]
With GHC 7.8.3, the following program is compiled into code that manipulates `Stream`s at runtime.

```haskell
module Foo where

import qualified Data.Vector.Unboxed as U

foo :: U.Vector Int -> U.Vector Int -> U.Vector Int
foo x y = U.map loop $ if U.null x then y else x

loop :: Int -> Int
loop x0 = go x0
  where
    go 0 = 0
    go x = 1 + go (x-1)
{-# INLINE loop #-}
```

For this problem to happen, `loop` doesn't have to be exactly this function, and it doesn't have to be recursive either. It just needs to be large enough that GHC doesn't automatically inline it.

A work-around is to replace the `INLINE` pragma for `loop` with `INLINE[0]`.

**Comment by cartazio** [comment]
how does the code optimize with vector HEAD/master?

**Comment by takano-akio** [comment]
@cartazio I'm not sure that I understand the question. Would you like to see the optimized core, or something else?

**Comment by glguy** [comment]
@cartazio  The "Stream" constructors optimize away in GHC 7.10.1-rc1 and GHC 7.11.20150120

**Comment by cartazio** [comment]
@glguy  in which case, its not really a bug on the vector side, but variability in how ghc optimizes, right?

**Comment by cartazio** [comment]
i've tried running your example code "good" vs "bad" benchmark locally with the most recent release of vector 0.11 on ghc 8.0.1 on os x with O2 optimization, and the timings seem to be essentially the same (only a ~ 10% difference but the total range of the times all lies in 80-100 microseconds)

so pending a code example that reproduces it with recent vector and ghc, i'm closing this and marking it invalid for now

**Comment by cartazio** [comment]
(that said, I really do appreciate that you provided code for the purposes of this bug)
