### ISSUE TITLE
Like constructN, but with map

### ISSUE THREAD

**Issue by yongqli** [haskell/vector#62]
I'm trying to build a new vector with `constructN`, but there isn't a easy way to take an input vector. I would like a function like `constructMap`, that takes a function and an input vector. The function is given access to the parts of the output vector already built and an element from the input vector. Is there an easy and efficient to way to do this that I'm missing?

**Comment by sjcjoosten** [comment]
Are you still looking for this? I managed to write this using the idea behind constructN. For f b, you can use v x.

```
import qualified Data.Vector as Vector
import Data.Vector.Generic.Base
import Data.Vector.Generic (unsafeFreeze, unsafeThaw, unsafeTake)
import qualified Data.Vector.Generic.Mutable as M
import Control.Monad.ST

constructNA :: forall v a f b. (Vector v a, Foldable f)
            => f b -> (Int -> v a -> b -> a) -> (v a)
{-# INLINE constructNA #-}
constructNA bs f
 = runST (
   do
     v  <- M.new n
     v' <- unsafeFreeze v
     checkNr$ foldl' fill (0, pure v') bs
   )
   where
     n = length bs
     fill :: forall s. (Int, ST s (v a)) -> b -> (Int, ST s (v a))
     fill (!i,!v) b
      = (i+1, do !v'' <- v
                 let x = f i (unsafeTake i v'') b
                 v' :: Mutable v s a <- unsafeThaw v''
                 M.unsafeWrite v' i x
                 unsafeFreeze v')
     -- fill v _ = return v
     checkNr :: forall s. (Int, ST s (v a)) -> ST s (v a)
     checkNr (nr,!v) = v
```

Similarly, I wrote a version which also accumulates Monad operations over the vector:
```
constructNAM :: forall v a m f b. (Vector v a, Foldable f, Monad m)
             => f b -> (Int -> v a -> b -> m a) -> m (v a)
{-# INLINE constructNAM #-}
constructNAM bs f
 = checkNr$ foldl' fill (0, pure (runST (do v <- M.new n
                                            unsafeFreeze v))) bs
   where
     n = length bs
     fill :: (Int, m (v a)) -> b -> (Int, m (v a))
     fill (!i,!msv) b
      = (i+1, do !v'' <- msv
                 x <- f i (unsafeTake i v'') b
                 return (runST (do v' <- unsafeThaw v''
                                   _ <- M.unsafeWrite v' i x
                                   unsafeFreeze v')
                        )
              )
     checkNr :: forall s. (Int, s) -> s
     checkNr (nr,!v) = v
```

So yes, it's definable in user land in Vector 0.11.0, but as I'd rather not use any operation that has `unsafe' in it, this would be a great and versatile function for building Vectors. For my purpose, this was a lot faster than building a Sequence (which has fast |>, but slower lookups on the intermediate (v a)).

**Comment by yongqli** [comment]
Thanks, looks cool! These days I'm programming in Rust, which fit my needs (speed) better.

**Comment by cartazio** [comment]
we may revisit this later,but closing for now
