### ISSUE TITLE
add Vector (a,b) -> (Vector a, Vector b) et al to Unboxed Vector and MVector

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#63]
I'd like this for Unboxed Vectors and MVector

roughly 

```
Unbox (a,b) =>Vector (a,b) -> (Vector a,Vector b)
Unbox (a,b) => (Vector a,Vector b) -> Vector (a,b)
Unbox (a,b) => (MVector s a,MVector s b) -> MVector s (a,b)
Unbox (a,b) =>MVector (a,b) -> (MVector a,MVector b)
```

should do this for `(,)`...`(,,,)` and `Complex` at least

**Comment by neongreen** [comment]
`unzip`* and `zip`* are already provided for unboxed vectors and they are O(1): https://github.com/haskell/vector/blob/master/internal/unbox-tuple-instances

This issue should probably be closed.

**Comment by ttuegel** [comment]
We also need the same for `Complex`.

**Comment by yongqli** [comment]
It would be great if there was a way to expose the underlying "structure of arrays". It might be too much to ask for though. See https://github.com/ekmett/linear/issues/61

**Comment by cartazio** [comment]
@yongqli  i have something like that in my numerical repo 
https://github.com/wellposed/numerical/blob/master/src/Numerical/Data/Vector/Pair.hs

**Comment by ekmett** [comment]
I personally would have no problem with exporting the constructors from somewhere.

**Comment by lehins** [comment]
Constructors for unboxed vectors have been exported from `Data.Vector.Unboxed.Base` from the beginning of time. It is an internal module as it very much should be, but it does not prevent others to shoot themselves in the foot.
