### ISSUE TITLE
add more helper utilities for the .Mutable modules in Vector

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#64]
the `.Mutable` modules are currently a bit impoverished. could use some more utilities

**Comment by osa1** [comment]
Is this for adding utilities like http://hackage.haskell.org/package/vector-0.11.0.0/docs/Data-Vector-Storable.html#g:29 to mutable ones? If so , a big :+1: from me.

**Comment by archblob** [comment]
Yes it is,  but as you can see I'm really lazy so it may take a while.

**Comment by cartazio** [comment]
@archblob any chance this is still lying in your queue? :) or it is open season?

**Comment by archblob** [comment]
It seems I still have a branch on my fork. Though now that I'm reminded  of this, it's pretty tempting.sigh.
But It's pretty much open season.

**Comment by paraseba** [comment]
Is this still planned?

Today I needed `elemIndex` for a mutable vector and I was disappointed when I couldn't find anything similar. In the ideal world, `elemIndex` could be extremely fast on unboxed mutable vectors, like [memchr](https://www.gnu.org/software/libc/manual/html_node/Search-Functions.html#Search-Functions) fast! This would be very useful in low level algorithms.

I might have some cycles, but no working knowledge of the vector package internals. How could I help get this issue moving?

**Comment by Shimuuar** [comment]
Closed in favor of #334
