### ISSUE TITLE
figure out allowing mutable vectors to handle monad stacks

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#65]
possibly by eg a breaking change to the api for 0.11 (or more likely 0.12) that either 
a) uses Monad-ST or 
b) rethinks PrmMonad and the primitive package

I think this should be on the table for 0.12, though its something that should be contemplated for 0.11

**Comment by cartazio** [comment]
I think the `MonadST` style api can still expose that exact same "raw interface"

a Control.Primitive.Unsafe could import the internals of the ST monad and define 
`primitive :: (State# (PrimState m) -> (# State# (PrimState m), a #)) -> m a`
by taking advantage of the ST constructors

```
newtype ST s a = ST (STRep s a)
type STRep s a = State# s -> (# State# s, a #)
```

**Comment by snoyberg** [comment]
> and its inverse is also definable with similar ease via liftST

I don't believe that's true, can you show what that looks like? I don't know how you would write something that allows you to convert a ReadterT IO into an IO.

I'm not sure which other breaking changes are planned, but I'm typically very hesitant about just heaping on extra breakage because we're already breaking other things.

**Comment by cartazio** [comment]
oh, i was thinking a bit tooo impredicatively, that I could essentially do `(forall m . MonadST m=> m a  )-> IO a ` or the like

anyways, @dolio  has sold me on the upgrading `PrimMonad`, lets make it happen! :) 
(though i think there should be some back and forth on that too)

**Comment by snoyberg** [comment]
I thought that might have been what you were thinking of, which comes out
to the same as just specializing to ST if I'm not  mistaken.

Anyway, how should we proceed? I can certainly send a pull request with the
changes I made so far and we can iterate on that.

**Comment by cartazio** [comment]
a) yup! (which is kinda a subtle thing to grasp i think)

b) thats probably a good way to role, though its ultimately @dolio 's call. but seems like a concrete starting point for making stuff happen. I suspect we'll have to bikeshed over the `primmonadinternal` class name or whatever

**Comment by cartazio** [comment]
@snoyberg to clarify: if we can cut a new major bump on primmonad for this in the next few days, i'm all for it

**Comment by snoyberg** [comment]
OK, I opened a pull request on this.

**Comment by dolio** [comment]
If I'm not mistaken, this was addressed when we split `PrimMonad`.
