### ISSUE TITLE
Does not build on profiled GHC 7.8.4

### ISSUE THREAD

**Issue by kgadek** [haskell/vector#67]
Just got GHC 7.8.4 with profiling. Removed `~/.cabal` and `~/.ghc`, then only `cabal update` and `cabal install`.

    $ cabal --version
    cabal-install version 1.22.0.0
    using version 1.22.0.0 of the Cabal library

    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.4

There is no difference b/w usual install or installing inside a sandbox, it fails with the following error.

    $ mkdir tmp-vectors-7.8.4-2
    $ cd tmp-vectors-7.8.4-2
    $ cabal sandbox init
    Writing a default package environment file to
    /home/kgadek/tmp-vectors-7.8.4-2/cabal.sandbox.config
    Creating a new sandbox at /home/kgadek/tmp-vectors-7.8.4-2/.cabal-sandbox

    $ cabal update
    Downloading the latest package list from hackage.haskell.org
    cabal install vector

    $ cabal install vector
    Resolving dependencies...
    Downloading primitive-0.5.4.0...
    Configuring primitive-0.5.4.0...
    Building primitive-0.5.4.0...
    Preprocessing library primitive-0.5.4.0...
    [ 1 of 10] Compiling Data.Primitive.Internal.Compat ( Data/Primitive/Internal/Compat.hs, dist/dist-sandbox-a39fb984/build/Data/Primitive/Internal/Compat.o )
    [ 2 of 10] Compiling Data.Primitive.MachDeps ( Data/Primitive/MachDeps.hs, dist/dist-sandbox-a39fb984/build/Data/Primitive/MachDeps.o )
    [ 3 of 10] Compiling Data.Primitive.Internal.Operations ( Data/Primitive/Internal/Operations.hs, dist/dist-sandbox-a39fb984/build/Data/Primitive/Internal/Operations.o )
    [ 4 of 10] Compiling Control.Monad.Primitive ( Control/Monad/Primitive.hs, dist/dist-sandbox-a39fb984/build/Control/Monad/Primitive.o )
    [ 5 of 10] Compiling Data.Primitive.Types ( Data/Primitive/Types.hs, dist/dist-sandbox-a39fb984/build/Data/Primitive/Types.o )
    [ 6 of 10] Compiling Data.Primitive.Array ( Data/Primitive/Array.hs, dist/dist-sandbox-a39fb984/build/Data/Primitive/Array.o )

    Data/Primitive/Array.hs:32:1: Warning:
        The import of ‘Control.Monad.ST’ is redundant
          except perhaps to import instances from ‘Control.Monad.ST’
        To import instances alone, use: import Control.Monad.ST()
    [ 7 of 10] Compiling Data.Primitive.ByteArray ( Data/Primitive/ByteArray.hs, dist/dist-sandbox-a39fb984/build/Data/Primitive/ByteArray.o )
    [ 8 of 10] Compiling Data.Primitive.Addr ( Data/Primitive/Addr.hs, dist/dist-sandbox-a39fb984/build/Data/Primitive/Addr.o )
    [ 9 of 10] Compiling Data.Primitive   ( Data/Primitive.hs, dist/dist-sandbox-a39fb984/build/Data/Primitive.o )
    [10 of 10] Compiling Data.Primitive.MutVar ( Data/Primitive/MutVar.hs, dist/dist-sandbox-a39fb984/build/Data/Primitive/MutVar.o )
    In-place registering primitive-0.5.4.0...
    Creating package registration file: /tmp/pkgConf-primitive-0.5.415608.0
    Installing library in
    /home/kgadek/tmp-vectors-7.8.4-2/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.4/primitive-0.5.4.0
    Registering primitive-0.5.4.0...
    Installed primitive-0.5.4.0
    Downloading vector-0.10.12.2...
    Configuring vector-0.10.12.2...
    Building vector-0.10.12.2...
    Preprocessing library vector-0.10.12.2...
    [ 1 of 19] Compiling Data.Vector.Storable.Internal ( Data/Vector/Storable/Internal.hs, dist/dist-sandbox-a39fb984/build/Data/Vector/Storable/Internal.o )
    [ 2 of 19] Compiling Data.Vector.Fusion.Util ( Data/Vector/Fusion/Util.hs, dist/dist-sandbox-a39fb984/build/Data/Vector/Fusion/Util.o )
    [ 3 of 19] Compiling Data.Vector.Fusion.Stream.Size ( Data/Vector/Fusion/Stream/Size.hs, dist/dist-sandbox-a39fb984/build/Data/Vector/Fusion/Stream/Size.o )

    Data/Vector/Fusion/Stream/Size.hs:25:10: Warning:
        No explicit implementation for
          ‘*’, ‘abs’, and ‘signum’
        In the instance declaration for ‘Num Size’
    [ 4 of 19] Compiling Data.Vector.Internal.Check ( Data/Vector/Internal/Check.hs, dist/dist-sandbox-a39fb984/build/Data/Vector/Internal/Check.o )
    [ 5 of 19] Compiling Data.Vector.Fusion.Stream.Monadic ( Data/Vector/Fusion/Stream/Monadic.hs, dist/dist-sandbox-a39fb984/build/Data/Vector/Fusion/Stream/Monadic.o )
    ghc: You can't call hscCompileCoreExpr in a profiled compiler
    Failed to install vector-0.10.12.2
    cabal: Error: some packages failed to install:
    vector-0.10.12.2 failed during the building phase. The exception was:
    ExitFailure 1

`ghc-pkg` outside of sandbox:

    /home/kgadek/.ghc-7.8.4/lib/ghc-7.8.4/package.conf.d:
        Cabal-1.18.1.5
        array-0.5.0.0
        base-4.7.0.2
        bin-package-db-0.0.0.0
        binary-0.7.1.0
        rts-1.0
        bytestring-0.10.4.0
        containers-0.5.5.1
        deepseq-1.3.0.2
        directory-1.2.1.0
        filepath-1.3.0.2
        (ghc-7.8.4)
        ghc-prim-0.3.1.0
        haskeline-0.7.1.2
        (haskell2010-1.1.2.0)
        (haskell98-2.0.0.3)
        hoopl-3.10.0.1
        hpc-0.6.0.1
        integer-gmp-0.5.1.0
        old-locale-1.0.0.6
        old-time-1.1.0.2
        pretty-1.1.1.1
        process-1.2.0.0
        template-haskell-2.9.0.0
        terminfo-0.4.0.0
        time-1.4.2
        transformers-0.3.0.0
        unix-2.7.0.1
        xhtml-3000.2.1

    /home/kgadek/.ghc/x86_64-linux-7.8.4/package.conf.d:
        Cabal-1.22.0.0
        HTTP-4000.2.19
        mtl-2.2.1
        network-2.6.0.2
        network-uri-2.6.0.1
        parsec-3.1.8
        primitive-0.5.4.0
        random-1.1
        stm-2.4.4
        text-1.2.0.4
        transformers-0.4.2.0
        zlib-0.5.4.2

**Comment by kgadek** [comment]
Oops, should have placed "with profiling" into the title…

**Comment by kgadek** [comment]
Will need to post issues a bit slower next time: http://osdir.com/ml/cvs-ghc@haskell.org/2010-12/msg00252.html . However the question remains: is it possible to circumvent this in `vector` package or `vector` is and will be uninstallable on profiled GHC?

**Comment by cartazio** [comment]
Vector is installable.  Something is wrong with your config.  Do you have
profiling set to true in your cabal config?   I'm afk but I'll ask more
questions when I'm by a computer

**Comment by cartazio** [comment]
OHHH, @kgadek  you should never EVER remove `~/.cabal`, because the default `~/.cabal/config` doesn't have library profiling set to `True`

thats you issue. could you please confirm then close the ticket or provide more information? 
Thanks!
-Carter

**Comment by kgadek** [comment]
Unfortunately this did not help. I - again - cleared the env (`~/.ghc`, `~/.cabal`) so to make it clear the problem is in `vectors` (or is it actually?).

    $ cabal --version
    cabal-install version 1.22.0.0
    using version 1.22.0.0 of the Cabal library 

    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.4

    # GHC 7.8.4 compiled with mk/build.mk containing `BuildFlavour = prof`

    $ cat .cabal/config
    -- Removed commented-out lines cut.
    -- These are defaults from cabal 1.16. After `cabal update` I've set `library-profiling: True`.

    remote-repo: hackage.haskell.org:http://hackage.haskell.org/packages/archive
    remote-repo-cache: /home/kgadek/.cabal/packages
    world-file: /home/kgadek/.cabal/world
    library-profiling: True
    build-summary: /home/kgadek/.cabal/logs/build.log
    remote-build-reporting: anonymous
    install-dirs user
    -- ...
    install-dirs global
    -- ...

    # In fresh sandbox:

    $ cabal install vector
    Resolving dependencies...
    Configuring primitive-0.5.4.0...
    Building primitive-0.5.4.0...
    Preprocessing library primitive-0.5.4.0...
    [ 1 of 10] Compiling Data.Primitive.Internal.Compat ( Data/Primitive/Internal/Compat.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/Internal/Compat.o )
    [ 2 of 10] Compiling Data.Primitive.MachDeps ( Data/Primitive/MachDeps.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/MachDeps.o )
    [ 3 of 10] Compiling Data.Primitive.Internal.Operations ( Data/Primitive/Internal/Operations.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/Internal/Operations.o )
    [ 4 of 10] Compiling Control.Monad.Primitive ( Control/Monad/Primitive.hs, dist/dist-sandbox-5dbc957c/build/Control/Monad/Primitive.o )
    [ 5 of 10] Compiling Data.Primitive.Types ( Data/Primitive/Types.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/Types.o )
    [ 6 of 10] Compiling Data.Primitive.Array ( Data/Primitive/Array.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/Array.o )
    [ 7 of 10] Compiling Data.Primitive.ByteArray ( Data/Primitive/ByteArray.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/ByteArray.o )
    [ 8 of 10] Compiling Data.Primitive.Addr ( Data/Primitive/Addr.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/Addr.o )
    [ 9 of 10] Compiling Data.Primitive   ( Data/Primitive.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive.o )
    [10 of 10] Compiling Data.Primitive.MutVar ( Data/Primitive/MutVar.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/MutVar.o )
    [ 1 of 10] Compiling Data.Primitive.Internal.Compat ( Data/Primitive/Internal/Compat.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/Internal/Compat.p_o )
    [ 2 of 10] Compiling Data.Primitive.MachDeps ( Data/Primitive/MachDeps.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/MachDeps.p_o )
    [ 3 of 10] Compiling Data.Primitive.Internal.Operations ( Data/Primitive/Internal/Operations.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/Internal/Operations.p_o )
    [ 4 of 10] Compiling Control.Monad.Primitive ( Control/Monad/Primitive.hs, dist/dist-sandbox-5dbc957c/build/Control/Monad/Primitive.p_o )
    [ 5 of 10] Compiling Data.Primitive.Types ( Data/Primitive/Types.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/Types.p_o )
    [ 6 of 10] Compiling Data.Primitive.Array ( Data/Primitive/Array.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/Array.p_o )
    [ 7 of 10] Compiling Data.Primitive.ByteArray ( Data/Primitive/ByteArray.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/ByteArray.p_o )
    [ 8 of 10] Compiling Data.Primitive.Addr ( Data/Primitive/Addr.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/Addr.p_o )
    [ 9 of 10] Compiling Data.Primitive   ( Data/Primitive.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive.p_o )
    [10 of 10] Compiling Data.Primitive.MutVar ( Data/Primitive/MutVar.hs, dist/dist-sandbox-5dbc957c/build/Data/Primitive/MutVar.p_o )
    In-place registering primitive-0.5.4.0...
    Creating package registration file: /tmp/pkgConf-primitive-0.5.46180.0
    Installing library in
    /home/kgadek/tmp-vectors-7.8.4-3/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.4/primitive-0.5.4.0
    Registering primitive-0.5.4.0...
    Installed primitive-0.5.4.0
    Configuring vector-0.10.12.2...
    Building vector-0.10.12.2...
    Preprocessing library vector-0.10.12.2...
    [ 1 of 19] Compiling Data.Vector.Storable.Internal ( Data/Vector/Storable/Internal.hs, dist/dist-sandbox-5dbc957c/build/Data/Vector/Storable/Internal.o )
    [ 2 of 19] Compiling Data.Vector.Fusion.Util ( Data/Vector/Fusion/Util.hs, dist/dist-sandbox-5dbc957c/build/Data/Vector/Fusion/Util.o )
    [ 3 of 19] Compiling Data.Vector.Fusion.Stream.Size ( Data/Vector/Fusion/Stream/Size.hs, dist/dist-sandbox-5dbc957c/build/Data/Vector/Fusion/Stream/Size.o )
    [ 4 of 19] Compiling Data.Vector.Internal.Check ( Data/Vector/Internal/Check.hs, dist/dist-sandbox-5dbc957c/build/Data/Vector/Internal/Check.o )
    [ 5 of 19] Compiling Data.Vector.Fusion.Stream.Monadic ( Data/Vector/Fusion/Stream/Monadic.hs, dist/dist-sandbox-5dbc957c/build/Data/Vector/Fusion/Stream/Monadic.o )
    Failed to install vector-0.10.12.2

If you need any further details, I'll be happy to provide them.

**Comment by cartazio** [comment]
0) never delete `~/.cabal`, please stop it, that doesnt help with debugging
1) does it build without a sandbox? it could simply be that 
2) could you post a gist.github.com paste of you current `~/.cabal/config`
3) use a PASTE link, so this page doesnt get tooo long
4) could you also paste (again via a gist link, because this will be long) the results of a `cabal -v3 build` 
5) WHOSE ghc build are you using? i think you have a bad ghc build possibly. 
6) i personally have 
```
library-profiling: True
shared: True
```
in my cabal config always

**Comment by cartazio** [comment]
also: vector works with my mac + my build of ghc.

**Comment by kgadek** [comment]
0) what's the actual harm? Never heard that removing `~/.cabal` & `~/.ghc` is bad and since I always start from scratch I think that it positively affects the reproductability. Or am I wrong?
1) no, does not help – see below
2,3,4) https://gist.github.com/kgadek/0ee89e95a67c9cb873c8
5) it's GHC 7.8.4 I have compiled (with 7.8.3). I have performed `make fulltest` and all seems okay.
6) I don't have `shared: True`, but that did not change anything

I'm also using mac btw.

**Comment by glguy** [comment]
Vector simply isn't a package that you can compile if you've compiled a profiled GHC.

@cartazio You can't reproduce the outcome because you aren't using a GHC compiled with build.mk:BuildFlavour=prof

**Comment by cartazio** [comment]
OHHH, you mean a GHC that IS for profiling GHC, not profiling libraries.

**Comment by ak3n** [comment]
Not sure, but maybe I have the same problem with [cross-compiling ghc-7.8.3](https://github.com/neurocyte/ghc-android).

```
Resolving dependencies...
Configuring vector-0.10.12.2...
Building vector-0.10.12.2...
Preprocessing library vector-0.10.12.2...
[ 1 of 19] Compiling Data.Vector.Storable.Internal ( Data/Vector/Storable/Internal.hs, dist/build/Data/Vector/Storable/Internal.o )
[ 2 of 19] Compiling Data.Vector.Fusion.Util ( Data/Vector/Fusion/Util.hs, dist/build/Data/Vector/Fusion/Util.o )
[ 3 of 19] Compiling Data.Vector.Fusion.Stream.Size ( Data/Vector/Fusion/Stream/Size.hs, dist/build/Data/Vector/Fusion/Stream/Size.o )

Data/Vector/Fusion/Stream/Size.hs:25:10: Warning:
    No explicit implementation for
      ‘*’, ‘abs’, and ‘signum’
    In the instance declaration for ‘Num Size’
[ 4 of 19] Compiling Data.Vector.Internal.Check ( Data/Vector/Internal/Check.hs, dist/build/Data/Vector/Internal/Check.o )
[ 5 of 19] Compiling Data.Vector.Fusion.Stream.Monadic ( Data/Vector/Fusion/Stream/Monadic.hs, dist/build/Data/Vector/Fusion/Stream/Monadic.o )
Loading package ghc-prim ... Failed to install vector-0.10.12.2
cabal: Error: some packages failed to install:
vector-0.10.12.2 failed during the building phase. The exception was:
ExitFailure (-11)

```

**Comment by kgadek** [comment]
@glguy, I believe it would be best for *some-future-guy-to-solve-this-issue* to state the possible reasons for "Vector simply isn't a package that you can compile if you've compiled a profiled GHC.". I don't have required knowledge yet.

**Comment by kgadek** [comment]
I assume this is… fixed?

**Comment by cartazio** [comment]
It's a ghc problem.

**Comment by kgadek** [comment]
> Vector simply isn't a package that you can compile if you've compiled a profiled GHC.

This^ doesn't sound like a GHC problem.

Anyway, could you give the link to the issue on GHC tracker that we're talking about (and maybe explain how it's related to this package not being able to compile)?

**Comment by glguy** [comment]
@kgadek  https://www.mail-archive.com/cvs-ghc@haskell.org/msg23576.html
