### ISSUE TITLE
unstreamM is not exported

### ISSUE THREAD

**Issue by yongqli** [haskell/vector#70]
We are trying to write a `scanlM` and `scanrM` for `vector`, but to do so it seems that we need `unstreamM`, which exists in `Generic.hs` but isn't exported. Is there a reason why it isn't?

**Comment by Shimuuar** [comment]
Yeah. I wanted `unstreamM` too on few occasions.

**Comment by Shimuuar** [comment]
Is there opposition to exporting `unstreamM`? It is necessary to writing monadic folds etc.

We also have `unstreamPrimM` which is used only for RULES-based specialization of `unstreamM` (#208 is related)

**Comment by cartazio** [comment]
probably fine, though i'll have more head space to think about it in a few
weeks after i recover from this release :)
