### ISSUE TITLE
zipR?

### ISSUE THREAD

**Issue by yongqli** [haskell/vector#72]
It is my understanding that:

    scanr f x0 $ zip xs ys

will not fuse, since `unstream` will not fuse with `streamR`. However, we can write an analogous `zipRWith`:

    zipRWith f xs ys = unstreamR (Stream.zipWith f (streamR xs) (streamR ys))

Would this be useful?

**Comment by cartazio** [comment]
without benchmarks its hard for us to evaluate if this matters. if you'd like to put some together, please share!
