### ISSUE TITLE
should mutable vectors provide Data,Generic and Show instances?

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#77]
Just noticed that we dont provide those, but I dont see any reason why we couldnt. At least Show!

thoughts?

**Comment by cartazio** [comment]
@dolio is this another thing we should consider fixing for vector 0.11?

**Comment by cartazio** [comment]
erm, after thinking about it a teeny bit more, a non monadic show would be very dangerous. But we *SHOULD* think about some sort of PrimShow class/primitive,that maybe gives a safe way of displaying mutable vectors

**Comment by Shimuuar** [comment]
Wouldn't `show <$> freeze` do?

**Comment by cartazio** [comment]
@Shimuuar  point. closing :)

**Comment by cartazio** [comment]
erm, Data and Generic are still worth discussing i think

**Comment by Shimuuar** [comment]
Well I think there's nothing wrong with Generic instance except it breaks
data abstraction. So it's unsafe.

As for Data AFAIR we don't even have proper instance for immutable vectors.
Some methods are bottom

**Comment by cartazio** [comment]
yeah, after more thought: CLOSING :)
