### ISSUE TITLE
Cannot catch uninitialized-element exception

### ISSUE THREAD

**Issue by bezirg** [haskell/vector#79]
- Tested with GHC-7.8.4 on vector *0.10.12.2* and *0.10.12.3*

```haskell
import qualified Data.Vector.Mutable as V
import Control.Exception
arr <- V.new 1000 :: IO (IOVector Int)

try $ V.read arr 0 :: IO (Either SomeException Int)
-- res throws Right *** Exception: Data.Vector.Mutable: uninitialised element

V.read arr 0 `catch` (\ (_ :: SomeException) -> return 3) :: IO Int
-- throws *** Exception: Data.Vector.Mutable: uninitialised element
```

Is this a bug? If not, how can I catch such an exception?

**Comment by dolio** [comment]
`Data.Vector(.Mutable)` defines lazy, boxed vectors. What you're doing is reading out an element that is undefined. This is why catching doesn't do anything. It's not an exception-throwing `IO` action, it's a normal `IO` action returning bottom.

If you want to promote the exception into `IO`, you should use something like `evaluate`.

**Comment by bezirg** [comment]
Thanks for this. It works now, but I still don't know what is the datatype of Exception that I am trying to catch. 

For now, I use `SomeException`. I tried `Control.Exception.ArrayException` but does not work.
I scanned the vector code, but I couldn't find any exception datatype. Any ideas?

**Comment by dolio** [comment]
The exception you are seeing is just a call to `error`. I believe you catch those with `ErrorCall`.

**Comment by bezirg** [comment]
It works, thanks. 
Although, I guess this error is not that descriptive and it might interfere with other error-calls.
