### ISSUE TITLE
Add unfoldM for vectors

### ISSUE THREAD

**Issue by ocharles** [haskell/vector#8]
We have this for `Stream` - should we also have monadic unfolds for the various `Vector` types? My use case is `SDL.pollEvent :: IO (Maybe Event)`, and I would like to poll for all events into a `Vector Event`. Unless I misunderstand something, using an unfold would be the most efficient way to do this.

Edit: I should note that I'd love to learn how to provide a pull request for this. If a maintainer agrees we should have this functionality, I will investigate how to make it so.

**Comment by RyanGlScott** [comment]
Indeed, this issue has been fixed. Closing.
