### ISSUE TITLE
Can we please have a new release?

### ISSUE THREAD

**Issue by tibbe** [haskell/vector#82]
It seems that my commit (fa96a338b6ea3cd65de8654b119ee15c4469b27d) from April 7, 2014 is still not live. Could we have a new release please?

Also, could the releases please be tagged in the git repo so we know which code has been released.

**Comment by cartazio** [comment]
Would this be on the 0.10 series or master?

**Comment by tibbe** [comment]
I'd like a release of master if it's in a releasable state.

**Comment by cartazio** [comment]
There's a few more changes we are in the process of merging into vector,
and we'd like to have them all be in a single major version release, unless
we're going to do new major versions of vector more often.

**Comment by dolio** [comment]
I'll try to move things along and get a new major release out soon. It wouldn't be the end of the world if we did yet another relatively soon after that, if some of the things don't make it in.

**Comment by dolio** [comment]
Sorry this has taken me so long. I've been in the middle of moving, which has taken a lot of my spare time. I'm finally done, though, so I can hopefully get this done over the weekend.

**Comment by dolio** [comment]
0.11.0.0 is published.
