### ISSUE TITLE
`indexM :: Vector a -> Int -> Maybe a` throws runtime error

### ISSUE THREAD

**Issue by wereHamster** [haskell/vector#95]
I was expecting it to return `Nothing` when the index is out of bounds, especially because there is an `unsafeIndexM` whose documentation says 'without bounds checks'. If `unsafeIndexM` has no bounds checks, then `indexM` does have, right? So why does it fail with a runtime error? I was expecting `indexM` to fail gracefully in monads which have `fail` (such as `Maybe`).

In general, when I see two related functions, and one is marked as *unsafe*, I expect the unsafe version to generate runtime errors and the other not to. Unless the documentation mentions runtime errors, which it doesn't (not even for the unsafe versions).

**Comment by wereHamster** [comment]
Actually, the function I was using is `headM`, in an attempt to have a *safe* `head`. There is `!?` for safe indexing, but writing `x !? 0` seemed not very expressive of my intentions.

**Comment by glguy** [comment]
Runtime errors are not unsafe. Unsafe refers to things which can violate memory safety.

The documentation explains what the value of "monadic indexing" functions. [Haddocks for indexM](http://hackage.haskell.org/package/vector-0.11.0.0/docs/Data-Vector-Generic.html#v:indexM)

**Comment by cartazio** [comment]
monadic indexing is useful for strictness, as @glguy  remarks

**Comment by vlatkoB** [comment]
I expected the same, to gracefully fail. `!? 0 ==  headM`. :-(
