### ISSUE TITLE
Bug in generate from Data.Vector.Unboxed

### ISSUE THREAD

**Issue by gwright83** [haskell/vector#99]
In ghc 7.8.4 with vector-0.10.12.3 (OS X 10.10.5), the following program fails in an infinite loop (both compiled and in ghci):
```haskell
module Main where

import qualified Data.Vector.Unboxed as V

vec :: V.Vector Int
vec = V.generate 10 (\n -> if n == 0 then 2 else n + vec V.! (n - 1))

main :: IO ()
main = putStrLn $ show vec
```
The output is
> bardeen:~ gwright$ ./test
> test: `<<loop>>`
> bardeen:~ gwright$

However, if I change to a boxed vector by importing `Data.Vector` instead of `Data.Vector.Unboxed`, I get
> bardeen:~ gwright$ ./test
> fromList [2,3,5,8,12,17,23,30,38,47]
> bardeen:~ gwright$

I suspect that the problem has something to do with the function `generate` applies containing a recursive reference to `vec`.

I ran across this while writing a function that evaluates Bessel functions of purely imaginary order.  There is a recurrence relation for the coefficients of the power series expansion that is very conveniently evaluated by applying `generate` to a function that references lower indexed values in the array.

**Comment by cartazio** [comment]
This isn't a bug in vector.

Your definition only works if you either a) compute the vector entries
lazily, which requires boxed values

 As an experiment, does the unboxed code work when compiled using O0? It
maybe be that it's fundamentally too strict for that lazy trick to work!

I think looking at the core ghc generates for the optimized file will help
you see this.  Additionally your code

**Comment by gwright83** [comment]
Hi Carter,
I understand the problem now.  The code compiled with -O0 fails in the same way.
So to implement my recurrence relation using unboxed Doubles I need to go directly to mutable unboxed arrays.

I still consider it a shortcoming of the documentation that this simple change produces a failure without a useful message.  Recurrence relations like the one I am evaluating are the bread and butter of numerical analysis.  I'll submit a patch to the documentation.

Thanks for your help.

**Comment by cartazio** [comment]
It's kinda a bit deeper than that.  Boxed vectors are a lazy data structure
, unboxed / storable vectors a strict.  I'm not sure if the documentation
of vector is the right place to put an exposition on the differences, but I
may very well be wrong.

For your use case, is there any resource or performance reason you can't
compute it using the boxed model, then rebuild it as an unboxed vector
after you've computed it?

**Comment by cartazio** [comment]
this is not a bug, its fundamental to boxed vs unboxed. this ticket should be closed. /cc @hvr @dolio  @ekmett  @luite

**Comment by gwright83** [comment]
Agreed.

**Comment by cartazio** [comment]
@gwright83  i think you are the only one aside from @dolio who can close your own ticket :)

**Comment by gwright83** [comment]
I will close it.  Thanks.

**Comment by GeorgeCo** [comment]
It seems to me that " Boxed vectors are a lazy data structure, unboxed / storable vectors a strict." should be documented but I couldn't find it. Fortunately Google leads here. Sure advanced Haskell programmers can figure this out but the behavior described here is puzzling and frustrating to beginners. Having this documented would make the package friendlier to beginners
